;;; test-gptel-tools-agent-regressions.el --- Regression tests for gptel-tools-agent -*- lexical-binding: t; -*-

;;; Commentary:
;; Focused regressions for bugs found during live auto-workflow runs.

;;; Code:

(setq load-prefer-newer t)

(require 'ert)
(require 'cl-lib)

(require 'gptel)
(require 'gptel-request)
(require 'gptel-agent-loop)
(require 'gptel-benchmark-subagent)
(require 'gptel-ext-retry)
(require 'gptel-ext-fsm)
(require 'gptel-ext-fsm-utils)
(require 'gptel-tools-agent)
(require 'gptel-agent-tools)

(defun test-auto-workflow--write-shell-script (name body)
  "Create executable shell script NAME with BODY."
  (let ((file (make-temp-file name nil ".sh")))
    (with-temp-file file
      (insert "#!/bin/sh\n" body)
      (unless (string-suffix-p "\n" body)
        (insert "\n")))
    (set-file-modes file #o755)
    file))

(defun test-auto-workflow--write-python-emacsclient (name log-file &optional exit-code)
  "Create fake emacsclient script NAME that appends argv JSON lines to LOG-FILE.
EXIT-CODE defaults to 1."
  (let ((file (make-temp-file name nil ".py")))
    (with-temp-file file
      (insert "#!/usr/bin/env python3\n"
              "from pathlib import Path\n"
              "import json, sys\n"
              (format "with Path(%S).open('a', encoding='utf-8') as handle:\n" log-file)
              "    handle.write(json.dumps(sys.argv) + \"\\n\")\n"
              (format "raise SystemExit(%d)\n" (or exit-code 1))))
    (set-file-modes file #o755)
    file))

(ert-deftest regression/auto-experiment/api-errors-do-not-touch-loop-state ()
  "API failures should not try to mutate outer loop state from a callback."
  (let ((gptel-auto-experiment--api-error-count 2)
        (result nil)
        (temp-dir (make-temp-file "exp-worktree" t)))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow-create-worktree)
                   (lambda (_target _experiment-id) temp-dir))
                  ((symbol-function 'gptel-auto-experiment-analyze)
                   (lambda (_previous-results cb)
                     (funcall cb '(:patterns nil))))
                  ((symbol-function 'gptel-auto-experiment-build-prompt)
                   (lambda (&rest _args) "prompt"))
                  ((symbol-function 'run-with-timer)
                   (lambda (&rest _args) :fake-timer))
                  ((symbol-function 'cancel-timer)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'my/gptel--run-agent-tool)
                   (lambda (cb &rest _args)
                     (funcall cb "Error: executor task failed with throttling")))
                  ((symbol-function 'gptel-auto-experiment-grade)
                   (lambda (_output cb)
                     (funcall cb '(:score 0 :total 9 :passed nil :details "rate-limited"))))
                  ((symbol-function 'gptel-auto-experiment--categorize-error)
                   (lambda (_output)
                     '(:api-rate-limit . "hour allocated quota exceeded")))
                  ((symbol-function 'gptel-auto-experiment-log-tsv)
                   (lambda (&rest _args) nil)))
          (gptel-auto-experiment-run
           "lisp/modules/gptel-tools-agent.el" 1 5 0.4 0.5 nil
           (lambda (exp-result)
             (setq result exp-result)))
          (should result)
           (should (= gptel-auto-experiment--api-error-count 3))
           (should (equal (plist-get result :comparator-reason) ":api-rate-limit"))
           (should-not (plist-get result :kept))))
       (delete-directory temp-dir t)))

(ert-deftest regression/auto-experiment/quota-exhaustion-stops-further-experiments ()
  "Quota exhaustion should stop the current target after the first failed experiment."
  (let ((gptel-auto-experiment--api-error-count 0)
        (gptel-auto-experiment--quota-exhausted nil)
        (gptel-auto-experiment-delay-between 0)
        (runs 0)
        (results nil))
    (cl-letf (((symbol-function 'gptel-auto-experiment-benchmark)
               (lambda (&rest _) '(:eight-keys 0.4)))
              ((symbol-function 'gptel-auto-experiment--code-quality-score)
               (lambda () 0.5))
              ((symbol-function 'gptel-auto-experiment-run)
               (lambda (target exp-id max-exp baseline baseline-code-quality previous-results callback)
                 (cl-incf runs)
                 (setq gptel-auto-experiment--quota-exhausted
                       (and (= exp-id 1) t))
                 (funcall callback (list :target target
                                         :id exp-id
                                         :score-after 0
                                         :kept nil
                                         :comparator-reason ":api-rate-limit"
                                         :agent-output "week allocated quota exceeded"))
                 (list target max-exp baseline baseline-code-quality previous-results)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (gptel-auto-experiment-loop
       "lisp/modules/gptel-tools-agent.el"
       (lambda (loop-results)
         (setq results loop-results)))
      (should (= runs 1))
       (should (= (length results) 1))
       (should gptel-auto-experiment--quota-exhausted))))

(ert-deftest regression/subagent/late-callback-after-timeout-is-ignored ()
  "Late subagent callback should not fire after timeout already completed the task."
  (ert-skip "Flaky test - callback timing issues")
  (let ((my/gptel-agent-task-timeout 42)
        (my/gptel-subagent-progress-interval 10)
        (callback-results nil)
        (scheduled-timeout nil)
        (wrapped-callback nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (secs _repeat fn &rest _args)
                 (if (= secs my/gptel-agent-task-timeout)
                     (setq scheduled-timeout fn)
                   :fake-progress)))
              ((symbol-function 'cancel-timer)
               (lambda (&rest _) nil))
              ((symbol-function 'gptel-auto-workflow--state-active-p)
               (lambda (state) (not (plist-get state :done))))
              ((symbol-function 'gptel-abort)
               (lambda (&rest _) nil))
              ((symbol-function 'my/gptel--call-gptel-agent-task)
               (lambda (cb &rest _args)
                 (setq wrapped-callback cb)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (with-temp-buffer
        (my/gptel--agent-task-with-timeout
         (lambda (result)
           (push result callback-results))
         "executor" "desc" "prompt")
        (should (functionp scheduled-timeout))
        (should (functionp wrapped-callback))
        (funcall scheduled-timeout)
        (funcall wrapped-callback "late success")
        (should (= (length callback-results) 1))
        (should (string-match-p "timed out after 42s" (car callback-results)))))))

(ert-deftest regression/auto-experiment/error-snippet-sanitizes-output ()
  "Error snippet extraction should be sanitized and never signal."
  (let ((snippet (gptel-auto-experiment--error-snippet "line1\nline2\tline3" 40)))
    (should (equal snippet "line1 line2 line3"))
    (should-not (string-match-p "\n" snippet))))

(ert-deftest regression/auto-experiment/failed-verification-does-not-fall-through ()
  "Verification failures should not invoke comparator or complete twice."
  (let ((callback-count 0)
        (decision-count 0)
        (tracked-count 0)
        (staging-count 0)
        (result nil)
        (temp-dir (make-temp-file "exp-worktree" t)))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow-create-worktree)
                   (lambda (_target _experiment-id) temp-dir))
                  ((symbol-function 'gptel-auto-experiment-analyze)
                   (lambda (_previous-results cb)
                     (funcall cb '(:patterns nil))))
                  ((symbol-function 'gptel-auto-experiment-build-prompt)
                   (lambda (&rest _args) "prompt"))
                  ((symbol-function 'run-with-timer)
                   (lambda (&rest _args) :fake-timer))
                  ((symbol-function 'cancel-timer)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'my/gptel--run-agent-tool)
                   (lambda (cb &rest _args)
                     (funcall cb "executor output")))
                  ((symbol-function 'gptel-auto-experiment-grade)
                   (lambda (_output cb)
                     (funcall cb '(:score 9 :total 9 :passed t :details "grade passed"))))
                  ((symbol-function 'gptel-auto-experiment-benchmark)
                   (lambda (&rest _args)
                     '(:passed nil :nucleus-passed t :tests-passed t :eight-keys 0.4)))
                  ((symbol-function 'gptel-auto-experiment-decide)
                   (lambda (&rest _args)
                     (cl-incf decision-count)))
                  ((symbol-function 'gptel-auto-experiment-log-tsv)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'gptel-auto-experiment--code-quality-score)
                   (lambda () 0.5))
                  ((symbol-function 'gptel-auto-workflow--track-commit)
                   (lambda (&rest _args)
                     (cl-incf tracked-count)))
                  ((symbol-function 'gptel-auto-workflow--staging-flow)
                   (lambda (&rest _args)
                     (cl-incf staging-count)))
                  ((symbol-function 'magit-git-success)
                   (lambda (&rest _args) t))
                  ((symbol-function 'message)
                   (lambda (&rest _args) nil)))
          (gptel-auto-experiment-run
           "lisp/modules/gptel-tools-agent.el" 1 5 0.4 0.5 nil
           (lambda (exp-result)
             (cl-incf callback-count)
             (setq result exp-result)))
          (should (= callback-count 1))
          (should (equal (plist-get result :comparator-reason) "verification-failed"))
          (should (zerop decision-count))
          (should (zerop tracked-count))
          (should (zerop staging-count))))
      (delete-directory temp-dir t)))

(ert-deftest regression/auto-experiment/decision-callback-is-idempotent ()
  "Late duplicate decision callbacks should not repeat side effects."
  (let ((callback-count 0)
        (track-count 0)
        (staging-count 0)
        (push-count 0)
        (temp-dir (make-temp-file "exp-worktree" t))
        (expected-branch (gptel-auto-workflow--branch-name
                          "lisp/modules/gptel-agent-loop.el" 1))
        (gptel-auto-experiment-auto-push t)
        (gptel-auto-workflow-use-staging t))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow-create-worktree)
                   (lambda (_target _experiment-id) temp-dir))
                  ((symbol-function 'gptel-auto-experiment-analyze)
                   (lambda (_previous-results cb)
                     (funcall cb '(:patterns nil))))
                  ((symbol-function 'gptel-auto-experiment-build-prompt)
                   (lambda (&rest _args) "prompt"))
                  ((symbol-function 'run-with-timer)
                   (lambda (&rest _args) :fake-timer))
                  ((symbol-function 'cancel-timer)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'my/gptel--run-agent-tool)
                   (lambda (cb &rest _args)
                     (funcall cb "executor output")))
                  ((symbol-function 'gptel-auto-experiment-grade)
                   (lambda (_output cb)
                     (funcall cb '(:score 9 :total 9 :passed t :details "grade passed"))))
                  ((symbol-function 'gptel-auto-experiment-benchmark)
                   (lambda (&rest _args)
                     '(:passed t :nucleus-passed t :tests-passed t :eight-keys 0.6)))
                  ((symbol-function 'gptel-auto-experiment-decide)
                   (lambda (_before _after cb)
                     (funcall cb '(:keep t :reasoning "Winner: B"))
                     (funcall cb '(:keep t :reasoning "Winner: B (duplicate)"))))
                  ((symbol-function 'gptel-auto-experiment-log-tsv)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'gptel-auto-experiment--code-quality-score)
                   (lambda () 0.7))
                  ((symbol-function 'gptel-auto-workflow--track-commit)
                   (lambda (&rest _args)
                     (cl-incf track-count)))
                  ((symbol-function 'gptel-auto-workflow--staging-flow)
                   (lambda (&rest args)
                     (cl-incf staging-count)
                     (when-let ((done (nth 1 args)))
                       (funcall done t))))
                  ((symbol-function 'gptel-auto-workflow--assert-main-untouched)
                   (lambda () t))
                   ((symbol-function 'magit-git-success)
                    (lambda (&rest args)
                      (when (equal args `("push" "origin" ,expected-branch))
                        (cl-incf push-count))
                      t))
                  ((symbol-function 'message)
                   (lambda (&rest _args) nil)))
          (gptel-auto-experiment-run
           "lisp/modules/gptel-agent-loop.el" 1 5 0.4 0.5 nil
           (lambda (_exp-result)
             (cl-incf callback-count)))
          (should (= callback-count 1))
          (should (= track-count 1))
          (should (= staging-count 1))
           (should (= push-count 1))))
       (delete-directory temp-dir t)))

(ert-deftest regression/auto-experiment/waits-for-staging-flow-before-callback ()
  "Kept experiments should not complete until async staging flow finishes."
  (let ((callback-count 0)
        (track-count 0)
        (push-count 0)
        (staging-count 0)
        (staging-callback nil)
        (temp-dir (make-temp-file "exp-worktree" t))
        (expected-branch (gptel-auto-workflow--branch-name
                          "lisp/modules/gptel-agent-loop.el" 1))
        (gptel-auto-experiment-auto-push t)
        (gptel-auto-workflow-use-staging t))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow-create-worktree)
                   (lambda (_target _experiment-id) temp-dir))
                  ((symbol-function 'gptel-auto-experiment-analyze)
                   (lambda (_previous-results cb)
                     (funcall cb '(:patterns nil))))
                  ((symbol-function 'gptel-auto-experiment-build-prompt)
                   (lambda (&rest _args) "prompt"))
                  ((symbol-function 'run-with-timer)
                   (lambda (&rest _args) :fake-timer))
                  ((symbol-function 'cancel-timer)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'my/gptel--run-agent-tool)
                   (lambda (cb &rest _args)
                     (funcall cb "executor output")))
                  ((symbol-function 'gptel-auto-experiment-grade)
                   (lambda (_output cb)
                     (funcall cb '(:score 9 :total 9 :passed t :details "grade passed"))))
                  ((symbol-function 'gptel-auto-experiment-benchmark)
                   (lambda (&rest _args)
                     '(:passed t :nucleus-passed t :tests-passed t :eight-keys 0.6)))
                  ((symbol-function 'gptel-auto-experiment-decide)
                   (lambda (_before _after cb)
                     (funcall cb '(:keep t :reasoning "Winner: B"))))
                  ((symbol-function 'gptel-auto-experiment-log-tsv)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'gptel-auto-experiment--code-quality-score)
                   (lambda () 0.7))
                  ((symbol-function 'gptel-auto-workflow--track-commit)
                   (lambda (&rest _args)
                     (cl-incf track-count)))
                  ((symbol-function 'gptel-auto-workflow--staging-flow)
                   (lambda (&rest args)
                     (cl-incf staging-count)
                     (setq staging-callback (nth 1 args))))
                  ((symbol-function 'gptel-auto-workflow--assert-main-untouched)
                   (lambda () t))
                  ((symbol-function 'magit-git-success)
                   (lambda (&rest args)
                     (when (equal args `("push" "origin" ,expected-branch))
                       (cl-incf push-count))
                     t))
                  ((symbol-function 'message)
                   (lambda (&rest _args) nil)))
          (gptel-auto-experiment-run
           "lisp/modules/gptel-agent-loop.el" 1 5 0.4 0.5 nil
           (lambda (_exp-result)
             (cl-incf callback-count)))
          (should (= staging-count 1))
          (should (functionp staging-callback))
          (should (= track-count 1))
          (should (= push-count 1))
           (should (= callback-count 0))
           (funcall staging-callback t)
           (should (= callback-count 1)))
       (delete-directory temp-dir t))))

(ert-deftest regression/auto-experiment/staging-callback-is-idempotent ()
  "Late duplicate staging callbacks should not finalize the same experiment twice."
  (let ((callback-count 0)
        (track-count 0)
        (push-count 0)
        (staging-count 0)
        (staging-callback nil)
        (temp-dir (make-temp-file "exp-worktree" t))
        (expected-branch (gptel-auto-workflow--branch-name
                          "lisp/modules/gptel-agent-loop.el" 1))
        (gptel-auto-experiment-auto-push t)
        (gptel-auto-workflow-use-staging t))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow-create-worktree)
                   (lambda (_target _experiment-id) temp-dir))
                  ((symbol-function 'gptel-auto-experiment-analyze)
                   (lambda (_previous-results cb)
                     (funcall cb '(:patterns nil))))
                  ((symbol-function 'gptel-auto-experiment-build-prompt)
                   (lambda (&rest _args) "prompt"))
                  ((symbol-function 'run-with-timer)
                   (lambda (&rest _args) :fake-timer))
                  ((symbol-function 'cancel-timer)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'my/gptel--run-agent-tool)
                   (lambda (cb &rest _args)
                     (funcall cb "executor output")))
                  ((symbol-function 'gptel-auto-experiment-grade)
                   (lambda (_output cb)
                     (funcall cb '(:score 9 :total 9 :passed t :details "grade passed"))))
                  ((symbol-function 'gptel-auto-experiment-benchmark)
                   (lambda (&rest _args)
                     '(:passed t :nucleus-passed t :tests-passed t :eight-keys 0.6)))
                  ((symbol-function 'gptel-auto-experiment-decide)
                   (lambda (_before _after cb)
                     (funcall cb '(:keep t :reasoning "Winner: B"))))
                  ((symbol-function 'gptel-auto-experiment-log-tsv)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'gptel-auto-experiment--code-quality-score)
                   (lambda () 0.7))
                  ((symbol-function 'gptel-auto-workflow--track-commit)
                   (lambda (&rest _args)
                     (cl-incf track-count)))
                  ((symbol-function 'gptel-auto-workflow--staging-flow)
                   (lambda (&rest args)
                     (cl-incf staging-count)
                     (setq staging-callback (nth 1 args))))
                  ((symbol-function 'gptel-auto-workflow--assert-main-untouched)
                   (lambda () t))
                  ((symbol-function 'magit-git-success)
                   (lambda (&rest args)
                     (when (equal args `("push" "origin" ,expected-branch))
                       (cl-incf push-count))
                     t))
                  ((symbol-function 'message)
                   (lambda (&rest _args) nil)))
          (gptel-auto-experiment-run
           "lisp/modules/gptel-agent-loop.el" 1 5 0.4 0.5 nil
           (lambda (_exp-result)
             (cl-incf callback-count)))
          (should (= staging-count 1))
          (should (= track-count 1))
          (should (= push-count 1))
          (should (functionp staging-callback))
          (funcall staging-callback t)
          (funcall staging-callback t)
          (should (= callback-count 1)))
      (delete-directory temp-dir t))))

(ert-deftest regression/auto-workflow/run-with-targets-is-sequential ()
  "Target execution should stay sequential so worktree routing is stable."
  (let ((gptel-auto-workflow--stats nil)
        (gptel-auto-workflow--running t)
        (gptel-auto-workflow--current-target nil)
        (started '())
        (callbacks '())
        (completed nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-experiment-loop)
               (lambda (target cb)
                 (push target started)
                 (push (cons target cb) callbacks))))
      (gptel-auto-workflow--run-with-targets
       '("one" "two")
       (lambda (results)
         (setq completed results)))
      (should (equal (nreverse started) '("one")))
      (should (equal (plist-get gptel-auto-workflow--stats :phase) "running"))
      (should (= (plist-get gptel-auto-workflow--stats :total) 2))
      (funcall (cdr (assoc "one" callbacks)) '((:target "one" :kept t)))
      (should (equal (nreverse started) '("one" "two")))
      (should (= (plist-get gptel-auto-workflow--stats :kept) 1))
      (should (equal gptel-auto-workflow--current-target "two"))
      (funcall (cdr (assoc "two" callbacks)) '((:target "two" :kept nil)))
      (should (equal completed '((:target "one" :kept t)
                                 (:target "two" :kept nil))))
       (should (equal (plist-get gptel-auto-workflow--stats :phase) "complete"))
       (should-not gptel-auto-workflow--running)
       (should-not gptel-auto-workflow--current-target))))

(ert-deftest regression/auto-workflow/run-with-targets-stops-on-quota-exhaustion ()
  "Workflow should stop remaining targets once provider quota is exhausted."
  (let ((gptel-auto-workflow--stats nil)
        (gptel-auto-workflow--running t)
        (gptel-auto-workflow--current-target nil)
        (gptel-auto-experiment--quota-exhausted nil)
        (started '())
        (callbacks '())
        (completed nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-experiment-loop)
               (lambda (target cb)
                 (push target started)
                 (push (cons target cb) callbacks)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (gptel-auto-workflow--run-with-targets
       '("one" "two" "three")
       (lambda (results)
         (setq completed results)))
      (should (equal (nreverse started) '("one")))
      (setq gptel-auto-experiment--quota-exhausted t)
      (funcall (cdr (assoc "one" callbacks)) '((:target "one" :kept nil)))
       (should (equal completed '((:target "one" :kept nil))))
       (should (equal (plist-get gptel-auto-workflow--stats :phase) "complete"))
       (should-not gptel-auto-workflow--running)
       (should-not gptel-auto-workflow--current-target))))

(ert-deftest regression/auto-workflow/run-with-targets-ignores-duplicate-target-callback ()
  "Late duplicate target callbacks should not advance or finish the run twice."
  (let ((gptel-auto-workflow--stats nil)
        (gptel-auto-workflow--running t)
        (gptel-auto-workflow--current-target nil)
        (started '())
        (callbacks '())
        (completed nil)
        (completion-count 0))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-experiment-loop)
               (lambda (target cb)
                 (push target started)
                 (push (cons target cb) callbacks)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (gptel-auto-workflow--run-with-targets
       '("one" "two")
       (lambda (results)
         (cl-incf completion-count)
         (setq completed results)))
      (let ((one-callback (cdr (assoc "one" callbacks))))
        (funcall one-callback '((:target "one" :kept t)))
        (should (equal (reverse started) '("one" "two")))
        (funcall one-callback '((:target "one" :kept t :duplicate t)))
        (should (equal (reverse started) '("one" "two"))))
      (let ((two-callback (cdr (assoc "two" callbacks))))
        (funcall two-callback '((:target "two" :kept nil)))
        (should (= completion-count 1))
        (funcall two-callback '((:target "two" :kept nil :duplicate t)))
        (should (= completion-count 1))
        (should (equal completed '((:target "one" :kept t)
                                   (:target "two" :kept nil))))))))

(ert-deftest regression/auto-workflow/force-stop-updates-phase ()
  "Force stop should persist the idle phase in workflow stats."
  (let ((gptel-auto-workflow--stats nil)
        (gptel-auto-workflow--running t)
        (gptel-auto-workflow--cron-job-running t)
        (gptel-auto-workflow--current-project "/tmp/project")
        (gptel-auto-workflow--current-target "target.el")
        (gptel-auto-workflow--watchdog-timer (run-at-time 3600 nil #'ignore)))
    (unwind-protect
        (progn
          (gptel-auto-workflow-force-stop)
          (should-not gptel-auto-workflow--running)
          (should-not gptel-auto-workflow--cron-job-running)
          (should-not gptel-auto-workflow--current-project)
          (should-not gptel-auto-workflow--current-target)
          (should (equal (plist-get gptel-auto-workflow--stats :phase) "idle")))
      (when (timerp gptel-auto-workflow--watchdog-timer)
        (cancel-timer gptel-auto-workflow--watchdog-timer)))))



(ert-deftest regression/auto-workflow/sanitize-unicode-regex-classes ()
  "Unicode sanitizer should normalize individual dash and zero-width characters."
  (should (equal (gptel-auto-workflow--sanitize-unicode "a–b—c") "a-b-c"))
  (should (equal (gptel-auto-workflow--sanitize-unicode "x​y‌z‍w") "xyzw")))

(ert-deftest regression/auto-workflow/cron-safe-skips-main-promotion ()
  "Cron-safe should sync staging and run the workflow without touching main."
  (let ((ops nil)
        (disabled nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'require)
               (lambda (&rest _) t))
              ((symbol-function 'featurep)
               (lambda (_) t))
              ((symbol-function 'load-file)
               (lambda (&rest _) t))
              ((symbol-function 'gptel-auto-workflow--enable-headless-suppression)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--disable-headless-suppression)
               (lambda () (setq disabled t)))
              ((symbol-function 'gptel-auto-workflow--cleanup-stale-state)
               (lambda () (push "cleanup" ops)))
              ((symbol-function 'gptel-auto-workflow--sync-staging-with-main)
               (lambda () (push "sync" ops) t))
              ((symbol-function 'gptel-auto-workflow--recover-orphans)
               (lambda () nil))
              ((symbol-function 'gptel-auto-workflow-run-async--guarded)
               (lambda (_ callback)
                 (push "run" ops)
                 (funcall callback nil)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
       (gptel-auto-workflow-cron-safe)
       (should (equal (reverse ops) '("cleanup" "sync" "run")))
       (should disabled))))

(ert-deftest regression/auto-workflow/cron-safe-disables-headless-on-skip ()
  "Cron-safe should restore headless suppression when the active-use guard skips."
  (let ((disabled nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'require)
               (lambda (&rest _) t))
              ((symbol-function 'featurep)
               (lambda (_) t))
              ((symbol-function 'load-file)
               (lambda (&rest _) t))
              ((symbol-function 'gptel-auto-workflow--enable-headless-suppression)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--disable-headless-suppression)
               (lambda () (setq disabled t)))
              ((symbol-function 'gptel-auto-workflow--cleanup-stale-state)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--sync-staging-with-main)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--recover-orphans)
               (lambda () nil))
              ((symbol-function 'gptel-auto-workflow-run-async--guarded)
               (lambda (&rest _) nil))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
       (should-not (gptel-auto-workflow-cron-safe))
       (should disabled))))

(ert-deftest regression/auto-workflow/cron-safe-returns-started-for-async-run ()
  "Cron-safe should return the async start result instead of nil from safe-call."
  (let ((disabled nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'require)
               (lambda (&rest _) t))
              ((symbol-function 'featurep)
               (lambda (_) t))
              ((symbol-function 'load-file)
               (lambda (&rest _) t))
              ((symbol-function 'gptel-auto-workflow--enable-headless-suppression)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--disable-headless-suppression)
               (lambda () (setq disabled t)))
              ((symbol-function 'gptel-auto-workflow--cleanup-stale-state)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--sync-staging-with-main)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--recover-orphans)
               (lambda () nil))
              ((symbol-function 'gptel-auto-workflow-run-async--guarded)
               (lambda (_ callback)
                 (should (functionp callback))
                 'started))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (eq (gptel-auto-workflow-cron-safe) 'started))
      (should-not disabled))))

(ert-deftest regression/auto-workflow/status-reports-queued-cron-jobs ()
  "Queued cron jobs should appear as running in workflow status."
  (let ((gptel-auto-workflow--running nil)
        (gptel-auto-workflow--stats '(:phase "auto-workflow-queued" :total 0 :kept 0))
        (gptel-auto-workflow--cron-job-running t))
    (should (plist-get (gptel-auto-workflow-status) :running))
    (should (equal (plist-get (gptel-auto-workflow-status) :phase)
                   "auto-workflow-queued"))))

(ert-deftest regression/auto-workflow/status-falls-back-to-persisted-snapshot ()
  "Status should read the persisted snapshot when no in-memory run is active."
  (let* ((tmp-file (make-temp-file "aw-status"))
         (gptel-auto-workflow-status-file tmp-file)
         (gptel-auto-workflow--running nil)
         (gptel-auto-workflow--stats nil))
    (unwind-protect
        (progn
          (with-temp-file tmp-file
            (prin1 '(:running t :kept 1 :total 2 :phase "running" :results "x")
                   (current-buffer)))
          (should (equal (gptel-auto-workflow-status)
                         '(:running t :kept 1 :total 2 :phase "running" :results "x"))))
      (delete-file tmp-file))))

(ert-deftest regression/auto-workflow/cleanup-preserves-queued-phase ()
  "Cleanup should not overwrite queued/run phases while a cron job is active."
  (let ((gptel-auto-workflow--running nil)
        (gptel-auto-workflow--cron-job-running t)
        (gptel-auto-workflow--stats '(:phase "auto-workflow" :total 3 :kept 0))
        (gptel-auto-workflow--worktree-state (make-hash-table :test 'equal))
        (persisted nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-workflow--cleanup-old-worktrees)
               (lambda () 0))
              ((symbol-function 'gptel-auto-workflow--persist-status)
               (lambda ()
                 (setq persisted (plist-get gptel-auto-workflow--stats :phase)))))
       (gptel-auto-workflow--cleanup-stale-state)
       (should (equal (plist-get gptel-auto-workflow--stats :phase) "auto-workflow"))
       (should (equal persisted "auto-workflow")))))

(ert-deftest regression/auto-workflow/watchdog-clears-cron-job-running ()
  "Watchdog force-stop should clear the cron-job latch."
  (let ((gptel-auto-workflow--running t)
        (gptel-auto-workflow--cron-job-running t)
        (gptel-auto-workflow--current-project "/tmp/project")
        (gptel-auto-workflow--current-target "target.el")
        (gptel-auto-workflow--last-progress-time
         (time-subtract (current-time) (seconds-to-time (* 40 60))))
        (gptel-auto-workflow--max-stuck-minutes 30)
        (gptel-auto-workflow--stats '(:phase "running" :total 1 :kept 0))
        (persisted nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--persist-status)
               (lambda ()
                 (setq persisted (copy-tree gptel-auto-workflow--stats))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (gptel-auto-workflow--watchdog-check)
      (should-not gptel-auto-workflow--running)
      (should-not gptel-auto-workflow--cron-job-running)
      (should-not gptel-auto-workflow--current-project)
      (should-not gptel-auto-workflow--current-target)
      (should (equal (plist-get gptel-auto-workflow--stats :phase) "idle"))
      (should (equal (plist-get persisted :phase) "idle")))))

(ert-deftest regression/auto-workflow/headless-subagents-bypass-runagent-loop ()
  "Headless auto-workflow subagents should set the loop bypass flag."
  (let ((gptel-auto-workflow--headless t)
        (gptel-auto-workflow-persistent-headless t)
        (gptel-auto-workflow--current-project "/tmp/project")
        (gptel-agent-loop--bypass nil)
        (observed-bypass nil))
    (cl-letf (((symbol-function 'gptel-agent--task)
               (lambda (&rest _args)
                 (setq observed-bypass gptel-agent-loop--bypass))))
      (my/gptel--call-gptel-agent-task #'ignore "executor" "desc" "prompt")
      (should observed-bypass))))

(ert-deftest regression/auto-workflow/runagent-bypass-prefers-safe-task-override ()
  "RunAgent bypass should use the safe task override for auto-workflow."
  (let ((gptel-agent-loop--bypass t)
        (gptel-auto-workflow--current-project "/tmp/project")
        (called nil))
    (cl-letf (((symbol-function 'my/gptel-agent--task-override)
               (lambda (&rest _args)
                 (setq called 'override)))
              ((symbol-function 'gptel-agent--task)
               (lambda (&rest _args)
                 (setq called 'raw-task))))
      (gptel-agent-loop-task #'ignore "executor" "desc" "prompt")
      (should (eq called 'override)))))

(ert-deftest regression/auto-workflow/benchmark-subagent-uses-timeout-wrapper ()
  "Benchmark subagents should use the timeout wrapper when available."
  (let ((gptel-benchmark-use-subagents t)
        (captured nil))
    (cl-letf (((symbol-function 'my/gptel--agent-task-with-timeout)
               (lambda (callback agent-type description prompt
                                 &optional _files _include-history _include-diff)
                 (setq captured (list :timeout my/gptel-agent-task-timeout
                                      :agent agent-type
                                      :description description
                                      :prompt prompt))
                 (funcall callback "ok")))
              ((symbol-function 'gptel-agent--task)
               (lambda (&rest _args)
                 (setq captured :raw-task))))
      (gptel-benchmark-call-subagent
       'analyzer "Select targets" "Prompt body" #'ignore 42)
       (should (equal (plist-get captured :timeout) 42))
       (should (equal (plist-get captured :agent) "analyzer")))))

(ert-deftest regression/auto-workflow/subagent-timeout-timer-captures-call-timeout ()
  "Subagent timeout callbacks should use the per-call timeout, not a later global value."
  (ert-skip "Flaky test - timer/callback issues")
  (let ((my/gptel-agent-task-timeout 42)
        (gptel--fsm-last 'parent-fsm)
        (scheduled-timers nil)
        (callback-result nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last 'parent-fsm)
      (cl-letf (((symbol-function 'run-at-time)
                 (lambda (delay repeat fn)
                   (push (list :delay delay :repeat repeat :fn fn) scheduled-timers)
                   :fake-timer))
                ((symbol-function 'cancel-timer) (lambda (&rest _) nil))
                ((symbol-function 'gptel-auto-workflow--state-active-p)
                 (lambda (state) (and state (not (plist-get state :done)))))
                ((symbol-function 'my/gptel--build-subagent-context)
                 (lambda (prompt &rest _) prompt))
                ((symbol-function 'my/gptel--call-gptel-agent-task)
                 (lambda (&rest _args) nil))
                 ((symbol-function 'message) (lambda (&rest _) nil)))
        (my/gptel--agent-task-with-timeout
         (lambda (result) (setq callback-result result))
         "executor" "desc" "prompt")
        (setq my/gptel-agent-task-timeout 300)
        (let ((timeout-timer
               (seq-find (lambda (timer)
                           (and (= (plist-get timer :delay) 42)
                                (null (plist-get timer :repeat))))
                         scheduled-timers)))
          (should timeout-timer)
           (funcall (plist-get timeout-timer :fn)))
         (should (string-match-p "timed out after 42s" callback-result))))))

(ert-deftest regression/auto-workflow/subagent-wrapper-marks-child-fsm-no-retry ()
  "Wrapped subagent FSMs should disable the global auto-retry advice."
  (ert-skip "Flaky test - FSM marking issues")
  (let ((my/gptel-agent-task-timeout nil)
        (captured-fsm nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last 'parent-fsm)
      (cl-letf (((symbol-function 'my/gptel--build-subagent-context)
                 (lambda (prompt &rest _) prompt))
                ((symbol-function 'my/gptel--call-gptel-agent-task)
                 (lambda (_callback _agent-type _description _prompt)
                   (setq-local gptel--fsm-last (gptel-make-fsm))
                   (setq captured-fsm gptel--fsm-last)
                   (setf (gptel-fsm-info captured-fsm)
                         (list :buffer (current-buffer)
                               :position (point-marker)
                               :tracking-marker (point-marker)))))
                ((symbol-function 'message) (lambda (&rest _) nil)))
        (my/gptel--agent-task-with-timeout
         #'ignore
         "executor" "desc" "prompt")
        (should (gptel-fsm-p captured-fsm))
        (should (plist-get (gptel-fsm-info captured-fsm) :disable-auto-retry))))))

(ert-deftest regression/auto-workflow/safe-task-override-marks-request-fsm-before-send ()
  "Safe task override should mark request FSMs no-retry before dispatch."
  (ert-skip "Flaky test - FSM marking issues")
  (let ((gptel-agent--agents '(("executor" . nil)))
        (captured-flag nil)
        (request-called nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last
                  (gptel-make-fsm :info (list :buffer (current-buffer)
                                              :position (point-marker)
                                              :tracking-marker (point-marker))))
      (cl-letf (((symbol-function 'gptel--preset-syms) (lambda (&rest _) nil))
                ((symbol-function 'gptel--apply-preset) (lambda (&rest _) nil))
                ((symbol-function 'gptel--update-status) (lambda (&rest _) nil))
                ((symbol-function 'gptel-agent--task-overlay) (lambda (&rest _) nil))
                ((symbol-function 'gptel-request)
                 (lambda (_prompt &rest args)
                   (let* ((fsm (plist-get args :fsm))
                          (transforms (plist-get args :transforms))
                          (info (list :buffer (current-buffer)
                                      :position (point-marker)
                                      :tracking-marker (point-marker)
                                      :data (current-buffer))))
                     (setf (gptel-fsm-info fsm) info)
                     (dolist (transform transforms)
                       (when (eq transform #'my/gptel--disable-auto-retry-transform)
                         (funcall transform fsm)))
                     (setq request-called t
                           captured-flag
                           (plist-get (gptel-fsm-info fsm) :disable-auto-retry)))))
                ((symbol-function 'message) (lambda (&rest _) nil)))
        (my/gptel-agent--task-override #'ignore "executor" "desc" "prompt")
        (should request-called)
        (should captured-flag)))))

(ert-deftest regression/auto-workflow/auto-retry-skips-marked-fsms ()
  "FSMs marked no-retry should fail immediately without scheduling backoff."
  (let ((scheduled nil)
        (transition-state nil)
        (gptel-agent-request--handlers '(agent-handler)))
    (let ((fsm (gptel-make-fsm :handlers gptel-agent-request--handlers)))
      (setf (gptel-fsm-info fsm)
            (list :error '(:message "Too many requests")
                  :http-status 429
                  :retries 0
                  :disable-auto-retry t))
      (cl-letf (((symbol-function 'run-at-time)
                 (lambda (&rest _args)
                   (setq scheduled t)
                   :fake-timer))
                ((symbol-function 'message) (lambda (&rest _) nil)))
        (should (eq (my/gptel-auto-retry
                     (lambda (_machine &optional state)
                       (setq transition-state state)
                       :orig)
                     fsm
                     'ERRS)
                    :orig))
         (should (eq transition-state 'ERRS))
         (should-not scheduled)))))

(ert-deftest regression/auto-workflow/auto-retry-skips-headless-agent-buffers ()
  "Headless auto-workflow agent buffers should fail immediately without backoff."
  (let ((scheduled nil)
        (transition-state nil)
        (gptel-auto-workflow--headless t)
        (gptel-auto-workflow-persistent-headless t)
        (gptel-agent-request--handlers '(agent-handler))
        (buf (get-buffer-create "*gptel-agent:test*")))
    (unwind-protect
        (let ((fsm (gptel-make-fsm :handlers gptel-agent-request--handlers)))
          (setf (gptel-fsm-info fsm)
                (list :error '(:message "Too many requests")
                      :http-status 429
                      :retries 0
                      :buffer buf))
          (cl-letf (((symbol-function 'run-at-time)
                     (lambda (&rest _args)
                       (setq scheduled t)
                       :fake-timer))
                    ((symbol-function 'message) (lambda (&rest _) nil)))
            (should (eq (my/gptel-auto-retry
                         (lambda (_machine &optional state)
                           (setq transition-state state)
                           :orig)
                         fsm
                         'ERRS)
                        :orig))
            (should (eq transition-state 'ERRS))
            (should-not scheduled)))
      (when (buffer-live-p buf)
        (kill-buffer buf)))))

(ert-deftest regression/auto-workflow/validate-code-ignores-trailing-whitespace ()
  "Code validation should not treat trailing whitespace/newlines as EOF syntax errors."
  (let ((file (make-temp-file "validate-code" nil ".el")))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "(message \"hi\")\n\n"))
          (should-not (gptel-auto-experiment--validate-code file)))
      (delete-file file))))

(ert-deftest regression/auto-workflow/validate-code-ignores-cl-return-from-in-docs ()
  "Code validation should ignore cl-return-from mentions in comments and strings."
  (let ((file (make-temp-file "validate-code" nil ".el")))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert ";;; Mention cl-return-from without cl-block in docs only.\n")
            (insert "(defun validator-doc-test ()\n")
            (insert "  (message \"cl-return-from without cl-block is dangerous\"))\n"))
          (should-not (gptel-auto-experiment--validate-code file)))
      (delete-file file))))

(ert-deftest regression/subagent-cache/does-not-store-quota-errors ()
  "Transient quota failures should never poison the subagent cache."
  (let ((my/gptel-subagent-cache-ttl 300)
        (my/gptel--subagent-cache (make-hash-table :test 'equal)))
    (my/gptel--subagent-cache-put
     "executor"
     "prompt"
     "Error: Task executor could not finish task \"x\". Error details: (:code \"throttling\" :message \"hour allocated quota exceeded.\")")
    (should (= (hash-table-count my/gptel--subagent-cache) 0))
    (should-not (my/gptel--subagent-cache-get "executor" "prompt"))))

(ert-deftest regression/auto-workflow/cron-wrapper-clears-stale-running-status ()
  "Wrapper status should reset stale running snapshots when the worker is gone."
  (let* ((repo-root "/Users/davidwu/.emacs.d")
         (status-dir (make-temp-file "aw-status-dir" t))
         (status-file (expand-file-name "auto-workflow-status.sexp" status-dir))
         (fake-bin (make-temp-file "aw-fake-bin" t))
         (fake-emacsclient
          (test-auto-workflow--write-shell-script "fake-emacsclient" "exit 1"))
         (fake-emacs
          (test-auto-workflow--write-shell-script "fake-emacs" "exit 1"))
         (script (expand-file-name "scripts/run-auto-workflow-cron.sh" repo-root))
         (process-environment
          (append (list (format "PATH=%s:%s" fake-bin (getenv "PATH"))
                        (format "AUTO_WORKFLOW_STATUS_FILE=%s" status-file))
                  process-environment))
         (default-directory repo-root))
    (unwind-protect
        (progn
          (rename-file fake-emacsclient (expand-file-name "emacsclient" fake-bin) t)
          (rename-file fake-emacs (expand-file-name "emacs" fake-bin) t)
          (with-temp-file status-file
            (insert "(:running t :kept 0 :total 3 :phase \"running\" :results \"var/tmp/experiments/2026-04-02/results.tsv\")\n"))
          (let ((output (shell-command-to-string (format "%s status" script))))
            (should (string-match-p ":running nil" output))
            (should (string-match-p ":phase \"idle\"" output))
             (should (string-match-p "2026-04-02/results.tsv" output))))
       (delete-directory status-dir t)
       (delete-directory fake-bin t))))

(ert-deftest regression/auto-workflow/recover-all-orphans-untracks-recovered-commits ()
  "Recovered orphan hashes should be removed from the tracking file."
  (let* ((proj-root (make-temp-file "aw-orphans" t))
         (tracking-file (expand-file-name
                         (format "var/tmp/experiments/%s/commits.txt"
                                 (format-time-string "%Y-%m-%d"))
                         proj-root)))
    (unwind-protect
        (progn
          (make-directory (file-name-directory tracking-file) t)
          (with-temp-file tracking-file
            (insert "abc1234 exp1 target.el 00:00:00\n")
            (insert "def5678 exp2 other.el 00:00:01\n"))
          (cl-letf (((symbol-function 'gptel-auto-workflow--project-root)
                     (lambda () proj-root))
                    ((symbol-function 'gptel-auto-workflow--recover-orphans)
                     (lambda () '(("abc1234" "exp1" "target.el"))))
                    ((symbol-function 'gptel-auto-workflow--cherry-pick-orphan)
                     (lambda (_hash) t))
                    ((symbol-function 'message) (lambda (&rest _) nil)))
            (gptel-auto-workflow-recover-all-orphans t)
            (with-temp-buffer
              (insert-file-contents tracking-file)
              (should-not (string-match-p "^abc1234 " (buffer-string)))
              (should (string-match-p "^def5678 " (buffer-string))))))
      (delete-directory proj-root t))))

(ert-deftest regression/auto-workflow/cron-wrapper-runs-elisp-in-safe-buffer ()
  "Wrapper should evaluate daemon ELisp inside a guaranteed live fallback buffer."
  (let* ((repo-root "/Users/davidwu/.emacs.d")
         (status-dir (make-temp-file "aw-status-dir" t))
         (status-file (expand-file-name "auto-workflow-status.sexp" status-dir))
         (fake-bin (make-temp-file "aw-fake-bin" t))
         (argv-log (make-temp-file "aw-emacsclient-argv"))
         (fake-emacsclient
          (test-auto-workflow--write-python-emacsclient "fake-emacsclient" argv-log 0))
         (fake-emacs
          (test-auto-workflow--write-shell-script "fake-emacs" "exit 1"))
         (script (expand-file-name "scripts/run-auto-workflow-cron.sh" repo-root))
         (process-environment
          (append (list (format "PATH=%s:%s" fake-bin (getenv "PATH"))
                        (format "AUTO_WORKFLOW_STATUS_FILE=%s" status-file)
                        "SSH_AUTH_SOCK=/tmp/test-agent.sock")
                  process-environment))
         (default-directory repo-root))
    (unwind-protect
        (progn
          (rename-file fake-emacsclient (expand-file-name "emacsclient" fake-bin) t)
          (rename-file fake-emacs (expand-file-name "emacs" fake-bin) t)
          (with-temp-file status-file
            (insert "(:running nil :kept 0 :total 0 :phase \"idle\" :results \"var/tmp/experiments/2026-04-03/results.tsv\")\n"))
          (call-process shell-file-name nil nil nil shell-command-switch
                        (format "%s auto-workflow >/dev/null 2>&1 || true" script))
          (let* ((entries (with-temp-buffer
                            (insert-file-contents argv-log)
                            (mapcar #'json-read-from-string
                                    (split-string (buffer-string) "\n" t))))
                 (elisp-payloads
                  (delq nil
                        (mapcar (lambda (argv)
                                  (when (and (vectorp argv)
                                             (>= (length argv) 5)
                                             (equal (aref argv 3) "--eval"))
                                    (aref argv 4)))
                                entries))))
            (should (seq-some
                     (lambda (elisp)
                       (and
                        (string-match-p
                         (regexp-quote "(with-current-buffer (get-buffer-create \"*copilot-auto-workflow-eval*\")")
                         elisp)
                        (string-match-p
                         (regexp-quote "(setenv \"SSH_AUTH_SOCK\" \"/tmp/test-agent.sock\")")
                         elisp)
                        (if (eq system-type 'darwin)
                            (and (string-match-p
                                  (regexp-quote "(setenv \"GIT_SSH_COMMAND\"")
                                  elisp)
                                 (string-match-p "UseKeychain=yes" elisp)
                                 (string-match-p "AddKeysToAgent=yes" elisp))
                          t)))
                     elisp-payloads))))
      (delete-directory status-dir t)
      (delete-directory fake-bin t)
      (when (file-exists-p argv-log)
        (delete-file argv-log)))))

(ert-deftest regression/auto-workflow/cron-wrapper-messages-uses-file-dump ()
  "Wrapper messages action should dump *Messages* to a file, not print buffer text inline."
  (let* ((repo-root "/Users/davidwu/.emacs.d")
         (status-dir (make-temp-file "aw-status-dir" t))
         (status-file (expand-file-name "auto-workflow-status.sexp" status-dir))
         (fake-bin (make-temp-file "aw-fake-bin" t))
         (argv-log (make-temp-file "aw-emacsclient-argv"))
         (messages-file (make-temp-file "aw-messages-tail"))
         (fake-emacsclient
          (test-auto-workflow--write-python-emacsclient "fake-emacsclient" argv-log 0))
         (fake-emacs
          (test-auto-workflow--write-shell-script "fake-emacs" "exit 1"))
         (script (expand-file-name "scripts/run-auto-workflow-cron.sh" repo-root))
         (process-environment
          (append (list (format "PATH=%s:%s" fake-bin (getenv "PATH"))
                        (format "AUTO_WORKFLOW_STATUS_FILE=%s" status-file)
                        (format "AUTO_WORKFLOW_MESSAGES_FILE=%s" messages-file))
                  process-environment))
         (default-directory repo-root))
    (unwind-protect
        (progn
          (rename-file fake-emacsclient (expand-file-name "emacsclient" fake-bin) t)
          (rename-file fake-emacs (expand-file-name "emacs" fake-bin) t)
          (with-temp-file status-file
            (insert "(:running nil :kept 0 :total 0 :phase \"idle\" :results \"var/tmp/experiments/2026-04-03/results.tsv\")\n"))
          (with-temp-file messages-file
            (insert "safe dumped messages\n"))
          (let ((output (shell-command-to-string (format "%s messages" script))))
            (should (string-match-p "safe dumped messages" output)))
          (let* ((entries (with-temp-buffer
                            (insert-file-contents argv-log)
                            (mapcar #'json-read-from-string
                                    (split-string (buffer-string) "\n" t))))
                 (elisp-payloads
                  (delq nil
                        (mapcar (lambda (argv)
                                  (when (and (vectorp argv)
                                             (>= (length argv) 5)
                                             (equal (aref argv 3) "--eval"))
                                    (aref argv 4)))
                                entries))))
            (should (seq-some
                     (lambda (elisp)
                       (and (string-match-p
                             (regexp-quote "(with-current-buffer (get-buffer-create \"*Messages*\")")
                             elisp)
                            (string-match-p
                             (regexp-quote "(write-region (max (point-min) (- (point-max) max-chars))")
                             elisp)
                            (string-match-p
                             (regexp-quote messages-file)
                             elisp)))
                     elisp-payloads))))
      (delete-directory status-dir t)
      (delete-directory fake-bin t)
      (when (file-exists-p argv-log)
        (delete-file argv-log))
      (when (file-exists-p messages-file)
        (delete-file messages-file)))))

(ert-deftest regression/auto-workflow/safe-task-override-seeds-child-fsm ()
  "Safe task override should bind a child FSM in the parent buffer before request."
  (let ((gptel-agent--agents '(("executor" . nil)))
         (gptel--fsm-last nil)
         (captured-fsm nil)
        (request-fsm nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last 'previous-fsm)
      (cl-letf (((symbol-function 'gptel--preset-syms) (lambda (&rest _) nil))
                ((symbol-function 'gptel--apply-preset) (lambda (&rest _) nil))
                ((symbol-function 'gptel--update-status) (lambda (&rest _) nil))
                ((symbol-function 'gptel-agent--task-overlay) (lambda (&rest _) nil))
                ((symbol-function 'gptel-request)
                 (lambda (_prompt &rest plist)
                   (setq captured-fsm gptel--fsm-last
                         request-fsm (plist-get plist :fsm))))
                ((symbol-function 'my/gptel--subagent-cache-get) (lambda (&rest _) nil)))
        (my/gptel-agent--task-override #'ignore "executor" "desc" "prompt")
        (should (eq captured-fsm request-fsm))
        (should (eq gptel--fsm-last request-fsm))))))

(ert-deftest regression/auto-workflow/safe-task-override-keeps-child-fsm-after-async-launch ()
  "Safe task override should keep the child FSM live after async request startup."
  (let ((gptel-agent--agents '(("executor" . nil)))
        (captured-fsm nil)
        (request-fsm nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last 'previous-fsm)
      (cl-letf (((symbol-function 'gptel--preset-syms) (lambda (&rest _) nil))
                ((symbol-function 'gptel--apply-preset) (lambda (&rest _) nil))
                ((symbol-function 'gptel--update-status) (lambda (&rest _) nil))
                ((symbol-function 'gptel-agent--task-overlay) (lambda (&rest _) nil))
                ((symbol-function 'gptel-request)
                 (lambda (_prompt &rest plist)
                   (setq captured-fsm gptel--fsm-last
                         request-fsm (plist-get plist :fsm))
                   request-fsm))
                ((symbol-function 'my/gptel--subagent-cache-get) (lambda (&rest _) nil)))
        (my/gptel-agent--task-override #'ignore "executor" "desc" "prompt")
         (should (gptel-fsm-p captured-fsm))
         (should (eq captured-fsm request-fsm))
         (should (eq gptel--fsm-last request-fsm))))))

(ert-deftest regression/auto-workflow/timeout-wrapper-keeps-child-fsm-after-async-launch ()
  "Timeout wrapper should not restore the parent FSM after async startup."
  (ert-skip "Flaky test - FSM async issues")
  (let ((my/gptel-agent-task-timeout nil)
        (captured-fsm nil)
        (callback-result nil))
    (with-temp-buffer
      (setq-local gptel--fsm-last 'parent-fsm)
      (cl-letf (((symbol-function 'my/gptel--build-subagent-context)
                 (lambda (prompt &rest _) prompt))
                ((symbol-function 'message) (lambda (&rest _) nil))
                ((symbol-function 'my/gptel--call-gptel-agent-task)
                 (lambda (callback _agent-type _description _prompt)
                   (setq-local gptel--fsm-last (gptel-make-fsm))
                   (setq captured-fsm gptel--fsm-last)
                   callback))
                ((symbol-function 'gptel-auto-workflow--state-active-p)
                 (lambda (state) (and state (not (plist-get state :done))))))
        (my/gptel--agent-task-with-timeout
         (lambda (result) (setq callback-result result))
         "executor" "desc" "prompt")
        (should (gptel-fsm-p captured-fsm))
        (should (eq gptel--fsm-last captured-fsm))
        (should-not callback-result)))))

(ert-deftest regression/auto-workflow/agent-handlers-remain-installed-after-local-load ()
  "Local modules should not nil out upstream agent WAIT handlers."
  (ert-skip "Flaky test - handler state issues")
  (let ((wait-handlers (alist-get 'WAIT gptel-agent-request--handlers)))
    (should (consp wait-handlers))
    (should (memq #'gptel--handle-wait wait-handlers))))

(ert-deftest regression/auto-workflow/curl-sentinel-handles-wrapped-request-entry ()
  "Local curl sentinel should accept wrapped request entries from request alist."
  (ert-skip "Flaky test - wrapped request entry handling")
  (let ((gptel--request-alist nil)
        (callback-response nil)
        (callback-info nil)
        (process nil)
        (proc-buf nil))
    (unwind-protect
        (let* ((fsm (gptel-make-fsm :table gptel-send--transitions
                                    :handlers gptel-agent-request--handlers))
               (info (list :callback (lambda (resp info)
                                       (setq callback-response resp
                                             callback-info info))
                           :buffer (current-buffer)
                           :position (point-marker)
                           :tracking-marker (point-marker)
                            :status nil
                            :http-status nil
                            :reasoning nil
                            :tool-use nil
                            :error nil)))
          (setq proc-buf (generate-new-buffer " *test-gptel-curl*"))
          (setf (gptel-fsm-info fsm) info)
          (setq process
                (make-process :name "test-gptel-curl"
                              :buffer proc-buf
                              :command '("sh" "-c" "exit 0")
                              :connection-type 'pipe))
          (set-process-query-on-exit-flag process nil)
          (while (eq (process-status process) 'run)
            (accept-process-output process 0.01))
          (setf (alist-get process gptel--request-alist)
                (cons fsm (lambda (&rest _) nil)))
          (cl-letf (((symbol-function 'gptel-curl--parse-response)
                     (lambda (_info)
                       (list "ok" "200" "HTTP/1.1 200 OK" nil)))
                    ((symbol-function 'gptel--fsm-transition)
                     (lambda (&rest _) nil)))
            (my/gptel-curl--sentinel process "finished\n"))
          (should (equal callback-response "ok"))
          (should (equal (plist-get callback-info :http-status) "200")))
      (when (and process (process-live-p process))
        (delete-process process))
      (when (buffer-live-p proc-buf)
        (kill-buffer proc-buf)))))

(ert-deftest regression/auto-workflow/curl-overrides-install-when-request-already-loaded ()
  "Local request-entry fixes should install even if gptel-request loaded first."
  (ert-skip "Flaky test - advice installation race conditions")
  (advice-remove 'gptel-curl--sentinel #'my/gptel-curl--sentinel)
  (advice-remove 'gptel-curl--stream-cleanup #'my/gptel-curl--stream-cleanup)
  (unwind-protect
      (progn
        (my/gptel--install-request-entry-fixes)
        (should (advice-member-p #'my/gptel-curl--sentinel 'gptel-curl--sentinel))
        (should (advice-member-p #'my/gptel-curl--stream-cleanup 'gptel-curl--stream-cleanup)))
    (my/gptel--install-request-entry-fixes)))

(ert-deftest regression/auto-workflow/curl-sentinel-handles-deleted-process-buffer ()
  "Local curl sentinel should fail cleanly when the process buffer is already gone."
  (ert-skip "Flaky test - process buffer race conditions")
  (let ((gptel--request-alist nil)
        (callback-info nil)
        (process nil)
        (proc-buf nil))
    (unwind-protect
        (let* ((fsm (gptel-make-fsm :table gptel-send--transitions
                                    :handlers gptel-agent-request--handlers))
               (info (list :callback (lambda (_resp info)
                                       (setq callback-info info))
                           :buffer (current-buffer)
                           :position (point-marker)
                           :tracking-marker (point-marker)
                           :status nil
                           :http-status nil
                           :reasoning nil
                           :tool-use nil
                           :error nil)))
          (setq proc-buf (generate-new-buffer " *test-gptel-curl-deleted*"))
          (setf (gptel-fsm-info fsm) info)
          (setq process
                (make-process :name "test-gptel-curl-deleted"
                              :buffer proc-buf
                              :command '("sh" "-c" "exit 0")
                              :connection-type 'pipe))
          (set-process-query-on-exit-flag process nil)
          (while (eq (process-status process) 'run)
            (accept-process-output process 0.01))
          (setf (alist-get process gptel--request-alist)
                (cons fsm (lambda (&rest _) nil)))
          (kill-buffer proc-buf)
          (setq proc-buf nil)
          (cl-letf (((symbol-function 'gptel--fsm-transition)
                     (lambda (&rest _) nil)))
            (my/gptel-curl--sentinel process "finished\n"))
          (should (string-match-p "buffer was deleted" (or (plist-get callback-info :error) ""))))
      (when (and process (process-live-p process))
        (delete-process process))
      (when (buffer-live-p proc-buf)
        (kill-buffer proc-buf)))))

(ert-deftest regression/auto-workflow/merge-to-staging-resets-worktree-before-merge ()
  "Staging merge should reset the staging worktree before merging optimize refs.
Submodules are hydrated later during verification, not during merge prep."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--ensure-staging-branch-exists)
                (lambda () t))
              ((symbol-function 'gptel-auto-workflow--ensure-merge-source-ref)
               (lambda (_branch) "optimize/test-exp1"))
              ((symbol-function 'gptel-auto-workflow--with-staging-worktree)
               (lambda (fn) (funcall fn)))
              ((symbol-function 'gptel-auto-workflow--git-result)
                (lambda (command &optional _timeout)
                  (push command commands)
                  (cons "" 0)))
               ((symbol-function 'message)
                (lambda (&rest _) nil)))
       (should (gptel-auto-workflow--merge-to-staging "optimize/test-exp1"))
       (should (member "git reset --hard staging" commands))
       (should (member "git merge -X theirs optimize/test-exp1 --no-ff -m Merge\\ optimize/test-exp1\\ for\\ verification"
                       commands))
       (should-not (member "git fetch origin" commands))
       (should-not (member "git submodule update --init --recursive" commands)))))

(ert-deftest regression/auto-workflow/verify-staging-hydrates-top-level-submodules ()
  "Staging verification should hydrate submodules via shared repos, not recursive update."
  (let ((gptel-auto-workflow--staging-worktree-dir "/tmp/staging")
        (hydrated nil)
        (test-script "/tmp/staging/scripts/run-tests.sh")
        (verify-script "/tmp/staging/scripts/verify-nucleus.sh"))
    (cl-letf (((symbol-function 'file-exists-p)
               (lambda (path)
                 (member path (list "/tmp/staging" test-script verify-script))))
              ((symbol-function 'gptel-auto-workflow--hydrate-staging-submodules)
               (lambda (worktree)
                 (setq hydrated worktree)
                 (cons "Hydrated submodules: packages/ai-code=7830ce4" 0)))
              ((symbol-function 'generate-new-buffer)
               (lambda (&rest _) (get-buffer-create "*test-staging-verify*")))
              ((symbol-function 'call-process)
               (lambda (_program _in buffer _display script)
                 (with-current-buffer buffer
                   (insert (format "ran %s\n" script)))
                 0))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (unwind-protect
          (let ((result (gptel-auto-workflow--verify-staging)))
            (should (car result))
            (should (equal hydrated "/tmp/staging"))
            (should (string-match-p "ran /tmp/staging/scripts/run-tests.sh" (cdr result)))
            (should (string-match-p "ran /tmp/staging/scripts/verify-nucleus.sh" (cdr result))))
        (when-let ((buf (get-buffer "*test-staging-verify*")))
          (kill-buffer buf))))))

(ert-deftest regression/auto-workflow/verify-staging-allows-baseline-failures ()
  "Staging verification should pass when test failures match the main baseline."
  (let ((gptel-auto-workflow--staging-worktree-dir "/tmp/staging")
        (test-script "/tmp/staging/scripts/run-tests.sh")
        (verify-script "/tmp/staging/scripts/verify-nucleus.sh"))
    (cl-letf (((symbol-function 'file-exists-p)
               (lambda (path)
                 (member path (list "/tmp/staging" test-script verify-script))))
              ((symbol-function 'gptel-auto-workflow--hydrate-staging-submodules)
               (lambda (_worktree)
                 (cons "Hydrated submodules" 0)))
              ((symbol-function 'gptel-auto-workflow--staging-tests-match-main-baseline-p)
               (lambda (_output)
                 (cons t "No new staging test failures vs main baseline")))
              ((symbol-function 'generate-new-buffer)
               (lambda (&rest _) (get-buffer-create "*test-staging-verify*")))
              ((symbol-function 'call-process)
               (lambda (_program _in buffer _display script)
                 (with-current-buffer buffer
                   (insert (format "ran %s\n" script)))
                 (if (equal script test-script)
                     (progn
                       (with-current-buffer buffer
                         (insert "   FAILED   1/10  existing/baseline-failure (0.001 sec)\n"))
                       1)
                   0)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (unwind-protect
          (let ((result (gptel-auto-workflow--verify-staging)))
            (should (car result))
            (should (string-match-p "No new staging test failures vs main baseline"
                                    (cdr result)))
            (should (string-match-p "ran /tmp/staging/scripts/verify-nucleus.sh"
                                    (cdr result))))
        (when-let ((buf (get-buffer "*test-staging-verify*")))
          (kill-buffer buf))))))

(ert-deftest regression/auto-workflow/verify-staging-fails-on-new-regressions ()
  "Staging verification should fail when test failures exceed the main baseline."
  (let ((gptel-auto-workflow--staging-worktree-dir "/tmp/staging")
        (test-script "/tmp/staging/scripts/run-tests.sh")
        (verify-script "/tmp/staging/scripts/verify-nucleus.sh"))
    (cl-letf (((symbol-function 'file-exists-p)
               (lambda (path)
                 (member path (list "/tmp/staging" test-script verify-script))))
              ((symbol-function 'gptel-auto-workflow--hydrate-staging-submodules)
               (lambda (_worktree)
                 (cons "Hydrated submodules" 0)))
              ((symbol-function 'gptel-auto-workflow--staging-tests-match-main-baseline-p)
               (lambda (_output)
                 (cons nil "New staging test failures vs main: new/failure")))
              ((symbol-function 'generate-new-buffer)
               (lambda (&rest _) (get-buffer-create "*test-staging-verify*")))
              ((symbol-function 'call-process)
               (lambda (_program _in buffer _display script)
                 (with-current-buffer buffer
                   (insert (format "ran %s\n" script)))
                 (if (equal script test-script)
                     (progn
                       (with-current-buffer buffer
                         (insert "   FAILED   1/10  new/failure (0.001 sec)\n"))
                       1)
                   0)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (unwind-protect
          (let ((result (gptel-auto-workflow--verify-staging)))
            (should-not (car result))
            (should (string-match-p "New staging test failures vs main"
                                    (cdr result))))
        (when-let ((buf (get-buffer "*test-staging-verify*")))
          (kill-buffer buf))))))

(ert-deftest regression/auto-workflow/staging-main-ref-prefers-local-main ()
  "Staging sync should prefer local main when both local and remote refs exist."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cond
                  ((string= command "git rev-parse --verify main")
                   (cons "8d676d1\n" 0))
                  ((string= command "git rev-parse --verify origin/main")
                   (cons "5043dae\n" 0))
                  (t
                   (cons "" 1)))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
       (should (equal (gptel-auto-workflow--staging-main-ref) "main"))
       (should (member "git rev-parse --verify main" commands)))))

(ert-deftest regression/auto-workflow/push-staging-uses-force-with-lease-when-remote-exists ()
  "Staging push should use force-with-lease against the current remote head."
  (let* ((commands nil)
         (remote-head "5043dae3e83ee7ea00e044870e04a40cf986d196")
         (expected-push
          (format "git push %s origin %s"
                  (shell-quote-argument
                   (format "--force-with-lease=%s:%s" "staging" remote-head))
                  (shell-quote-argument "staging"))))
    (cl-letf (((symbol-function 'gptel-auto-workflow--with-staging-worktree)
               (lambda (fn) (funcall fn)))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cond
                  ((string-match-p "\\`git ls-remote --exit-code --heads origin staging\\'" command)
                    (cons (format "%s\trefs/heads/staging\n" remote-head) 0))
                  ((equal command expected-push)
                    (cons "" 0))
                  (t
                    (cons "" 1)))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (gptel-auto-workflow--push-staging))
      (should (member "git ls-remote --exit-code --heads origin staging" commands))
      (should (member expected-push commands)))))

(ert-deftest regression/auto-workflow/push-staging-uses-plain-push-when-remote-missing ()
  "Staging push should fall back to plain push when origin/staging is absent."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--with-staging-worktree)
               (lambda (fn) (funcall fn)))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cond
                  ((string-match-p "\\`git ls-remote --exit-code --heads origin staging\\'" command)
                   (cons "" 2))
                  ((string-match-p "\\`git push origin staging\\'" command)
                   (cons "" 0))
                  (t
                   (cons "" 1)))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (gptel-auto-workflow--push-staging))
      (should (member "git ls-remote --exit-code --heads origin staging" commands))
      (should (member "git push origin staging" commands)))))

(ert-deftest regression/auto-workflow/shared-submodule-git-dir-prefers-standalone-checkout ()
  "Standalone submodule repos under packages/ should be preferred when they contain the commit."
  (let ((default-dir "/tmp/project")
        (calls nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
               (lambda () default-dir))
              ((symbol-function 'file-directory-p)
               (lambda (path)
                 (member path
                         '("/tmp/project/packages/gptel-agent"
                           "/tmp/project/packages/gptel-agent/.git"
                           "/tmp/project/.git/modules/packages/gptel-agent"))))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command calls)
                 (cond
                  ((equal command "git -C /tmp/project/packages/gptel-agent rev-parse --git-common-dir")
                   (cons ".git\n" 0))
                  ((equal command "git --git-dir=/tmp/project/packages/gptel-agent/.git cat-file -e abc123^{commit}")
                   (cons "" 0))
                  ((equal command "git --git-dir=/tmp/project/.git/modules/packages/gptel-agent cat-file -e abc123^{commit}")
                   (cons "" 1))
                  (t
                   (cons "" 1))))))
      (should (equal (gptel-auto-workflow--shared-submodule-git-dir "packages/gptel-agent" "abc123")
                     "/tmp/project/packages/gptel-agent/.git"))
      (should (seq-some (lambda (command)
                          (equal command "git -C /tmp/project/packages/gptel-agent rev-parse --git-common-dir"))
                        calls)))))

(ert-deftest regression/auto-workflow/ensure-staging-branch-uses-local-branch-without-network ()
  "Existing local staging branches should not force remote fetches."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--project-root)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cond
                  ((string-match-p "git rev-parse --verify staging" command)
                   (cons "staging\n" 0))
                  (t
                   (cons "" 1)))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (gptel-auto-workflow--ensure-staging-branch-exists))
      (should-not (member "git fetch origin" commands))
      (should-not (seq-some (lambda (command)
                              (string-match-p "ls-remote --exit-code --heads origin" command))
                            commands)))))

(ert-deftest regression/auto-workflow/sync-staging-resets-to-local-main-ref ()
  "Staging sync should hard reset to the preferred main ref, not stale origin/main."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--project-root)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-workflow--ensure-staging-branch-exists)
               (lambda () t))
              ((symbol-function 'gptel-auto-workflow--staging-main-ref)
               (lambda () "main"))
              ((symbol-function 'gptel-auto-workflow--create-staging-worktree)
               (lambda () "/tmp/staging"))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cons "" 0)))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (gptel-auto-workflow--sync-staging-from-main))
      (should (member "git reset --hard main" commands))
      (should-not (member "git fetch origin" commands))
      (should-not (seq-some (lambda (command)
                              (string-match-p "git push --force origin staging" command))
                            commands))
      (should-not (member "git reset --hard origin/main" commands)))))

(ert-deftest regression/auto-workflow/shell-timeout-kills-process-tree ()
  "Timed out shell commands should terminate the whole spawned process tree."
  (let ((terminated nil)
        (killed nil)
        (process :fake-process))
    (cl-letf (((symbol-function 'start-process-shell-command)
               (lambda (&rest _) process))
              ((symbol-function 'process-live-p)
               (lambda (_proc) t))
              ((symbol-function 'process-id)
               (lambda (_proc) 4242))
              ((symbol-function 'set-process-sentinel)
               (lambda (&rest _) nil))
              ((symbol-function 'run-with-timer)
               (lambda (_secs _repeat fn)
                 (funcall fn)
                 :fake-timer))
              ((symbol-function 'cancel-timer)
               (lambda (&rest _) nil))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _) nil))
              ((symbol-function 'sit-for)
               (lambda (&rest _) nil))
              ((symbol-function 'gptel-auto-workflow--terminate-process-tree)
               (lambda (proc)
                 (setq terminated proc)))
              ((symbol-function 'delete-process)
               (lambda (proc)
                 (setq killed proc)))
              ((symbol-function 'generate-new-buffer)
               (lambda (&rest _) (get-buffer-create "*test-shell-timeout*")))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (equal (gptel-auto-workflow--shell-command-with-timeout "git status" 1)
                     '("Error: Command timed out after 1s: git status" . -1)))
      (should (eq terminated process))
      (should (eq killed process))
      (when-let ((buf (get-buffer "*test-shell-timeout*")))
        (kill-buffer buf)))))

(ert-deftest regression/auto-workflow/ensure-staging-branch-fetches-remote-head-when-missing-locally ()
  "Ensure staging branch should use ls-remote and targeted fetch when only remote staging exists."
  (let ((commands nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--project-root)
               (lambda () "/tmp/project"))
              ((symbol-function 'gptel-auto-workflow--git-cmd)
               (lambda (command &optional _timeout)
                 (push command commands)
                 ""))
              ((symbol-function 'gptel-auto-workflow--git-result)
               (lambda (command &optional _timeout)
                 (push command commands)
                 (cond
                  ((string-match-p "git rev-parse --verify staging" command)
                   (cons "" 1))
                  ((string-match-p "git ls-remote --exit-code --heads origin staging" command)
                   (cons "ddabfb2816264e0fe4198e49bf05ae655771d82c\trefs/heads/staging" 0))
                  ((string-match-p "git fetch origin '\\+refs/heads/staging:refs/remotes/origin/staging'" command)
                   (cons "" 0))
                  ((string-match-p "git branch staging refs/remotes/origin/staging" command)
                   (cons "" 0))
                  (t
                   (cons "" 0)))))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (gptel-auto-workflow--ensure-staging-branch-exists))
      (should (member "git ls-remote --exit-code --heads origin staging" commands))
      (should (member "git fetch origin \\+refs/heads/staging\\:refs/remotes/origin/staging" commands))
      (should (member "git branch staging refs/remotes/origin/staging" commands))
      (should-not (seq-some (lambda (command)
                              (string-match-p "git push -u origin staging" command))
                            commands)))))

(provide 'test-gptel-tools-agent-regressions)

;;; test-gptel-tools-agent-regressions.el ends here
