;;; test-gptel-auto-workflow-projects-regressions.el --- Regressions for project routing -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)

(require 'gptel-auto-workflow-projects)

(defvar gptel-auto-workflow--current-project nil)
(defvar gptel-auto-workflow--current-target nil)
(defvar gptel-auto-workflow-worktree-base nil)

(ert-deftest regression/auto-workflow-projects/task-routing-uses-target-worktree-by-default ()
  "Executor routing should use the recorded target worktree even when base is defaulted."
  (let* ((project-root (make-temp-file "aw-project" t))
         (worktree-dir (expand-file-name "var/tmp/experiments/optimize/foo-exp1" project-root))
         (gptel-auto-workflow--current-project project-root)
         (gptel-auto-workflow--current-target "packages/gptel/gptel-request.el")
         (gptel-auto-workflow-worktree-base nil)
         (captured-default-directory nil)
         (captured-buffer nil))
    (unwind-protect
        (progn
          (make-directory worktree-dir t)
          (cl-letf (((symbol-function 'my/gptel--subagent-cache-get) (lambda (&rest _) nil))
                    ((symbol-function 'my/gptel-agent--task-override)
                     (lambda (&rest _)
                       (setq captured-default-directory default-directory
                             captured-buffer (current-buffer))))
                    ((symbol-function 'gptel-auto-workflow--get-project-for-context)
                     (lambda ()
                       (cons project-root (get-buffer-create "*aw-project-root*"))))
                    ((symbol-function 'gptel-auto-workflow--get-worktree-dir)
                     (lambda (_target) worktree-dir))
                    ((symbol-function 'gptel-auto-workflow--get-worktree-buffer)
                     (lambda (dir)
                       (let ((buf (get-buffer-create "*aw-worktree*")))
                         (with-current-buffer buf
                           (setq-local default-directory (file-name-as-directory dir)))
                         buf)))
                    ((symbol-function 'gptel-fsm-info)
                     (lambda (&optional _fsm) nil)))
             (gptel-auto-workflow--advice-task-override
              (lambda (_main-cb _agent-type _description _prompt)
                (setq captured-default-directory default-directory
                      captured-buffer (current-buffer)))
             (lambda (_result) nil)
             "executor"
             "desc"
             "prompt")
            (should (equal (file-name-as-directory captured-default-directory)
                           (file-name-as-directory worktree-dir)))
            (should (equal (buffer-name captured-buffer) "*aw-worktree*"))))
      (delete-directory project-root t)
       (when (get-buffer "*aw-project-root*")
         (kill-buffer "*aw-project-root*"))
        (when (get-buffer "*aw-worktree*")
          (kill-buffer "*aw-worktree*")))))

(ert-deftest regression/auto-workflow-projects/executor-routing-refuses-project-root-fallback-without-worktree ()
  "Executor routing should fail closed instead of editing the project root."
  (let* ((project-root (make-temp-file "aw-project" t))
         (gptel-auto-workflow--current-project project-root)
         (gptel-auto-workflow--current-target "lisp/modules/gptel-ext-context-cache.el")
         (gptel-auto-workflow-worktree-base nil)
         (captured-result nil)
         (task-called nil))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'my/gptel--subagent-cache-get) (lambda (&rest _) nil))
                    ((symbol-function 'my/gptel-agent--task-override)
                     (lambda (&rest _args)
                       (setq task-called t)))
                    ((symbol-function 'gptel-auto-workflow--get-project-for-context)
                     (lambda ()
                       (cons project-root (get-buffer-create "*aw-project-root*"))))
                    ((symbol-function 'gptel-auto-workflow--get-worktree-dir)
                     (lambda (_target) nil))
                    ((symbol-function 'message) (lambda (&rest _) nil)))
            (let ((default-directory project-root))
              (gptel-auto-workflow--advice-task-override
               (lambda (&rest _args)
                 (setq task-called t))
               (lambda (result) (setq captured-result result))
               "executor"
               "Fix review issues"
               "prompt")))
          (should-not task-called)
          (should (string-match-p "Missing worktree context for executor task"
                                  captured-result)))
      (delete-directory project-root t)
      (when (get-buffer "*aw-project-root*")
        (kill-buffer "*aw-project-root*")))))

(ert-deftest regression/auto-workflow-projects/task-routing-exposes-buffer-tools-during-launch ()
  "Routed placeholder FSM info should inherit the target buffer's tools."
  (let ((expected-tools '("Code_Map" "Read" "Bash")))
    (unwind-protect
        (with-temp-buffer
          (setq-local gptel-use-tools t)
          (setq-local gptel-tools expected-tools)
          (let* ((marker (point-marker))
                 (info (gptel-auto-workflow--routed-fsm-info
                        '(:buffer other :position 1 :tracking-marker 1)
                        (current-buffer)
                        marker)))
            (should (eq (plist-get info :buffer) (current-buffer)))
            (should (eq (plist-get info :position) marker))
            (should (eq (plist-get info :tracking-marker) marker))
            (should (equal (plist-get info :tools) expected-tools))))
      nil)))

(ert-deftest regression/auto-workflow-projects/queue-helper-returns-before-job-runs ()
  "Queued cron work should not run inline in the `emacsclient' request."
  (let ((gptel-auto-workflow--cron-job-running nil)
        (gptel-auto-workflow--cron-job-timer nil)
        (job-ran nil)
        (scheduled nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_secs _repeat fn)
                  (setq scheduled fn)
                  'fake-timer))
              ((symbol-function 'gptel-auto-workflow--persist-status)
               (lambda (&rest _) nil)))
      (should
       (eq (gptel-auto-workflow--queue-cron-job
            "auto-workflow"
            (lambda () (setq job-ran t)))
           'queued))
      (should gptel-auto-workflow--cron-job-running)
      (should (eq gptel-auto-workflow--cron-job-timer 'fake-timer))
      (should-not job-ran)
      (should (functionp scheduled))
      (funcall scheduled)
      (should job-ran)
      (should-not gptel-auto-workflow--cron-job-running)
      (should-not gptel-auto-workflow--cron-job-timer))))

(ert-deftest regression/auto-workflow-projects/queue-helper-rejects-overlap ()
  "A second cron request should return immediately when one is already queued."
  (let ((gptel-auto-workflow--cron-job-running t)
        (scheduled nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest _)
                  (setq scheduled t)
                  'fake-timer))
              ((symbol-function 'gptel-auto-workflow--persist-status)
               (lambda (&rest _) nil)))
      (should
       (eq (gptel-auto-workflow--queue-cron-job
            "auto-workflow"
            (lambda ()))
           'already-running))
       (should-not scheduled)
       (should gptel-auto-workflow--cron-job-running))))

(ert-deftest regression/auto-workflow-projects/queue-helper-rejects-active-workflow ()
  "Queued cron requests should not replace an already running workflow."
  (let ((gptel-auto-workflow--cron-job-running nil)
        (gptel-auto-workflow--running t)
        (scheduled nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest _)
                 (setq scheduled t)
                 'fake-timer))
              ((symbol-function 'gptel-auto-workflow--persist-status)
               (lambda (&rest _) nil)))
      (should
       (eq (gptel-auto-workflow--queue-cron-job
            "auto-workflow"
            (lambda ()))
           'already-running))
       (should-not scheduled)
       (should gptel-auto-workflow--running)
       (should-not gptel-auto-workflow--cron-job-running))))

(ert-deftest regression/auto-workflow-projects/research-status-cache-recovers-from-malformed-entry ()
  "Malformed staged cache entries should be ignored and rewritten safely."
  (let* ((project-root "/tmp/project-a")
         (gptel-auto-workflow-projects (list project-root))
         (gptel-auto-workflow--research-findings-cache (make-hash-table :test 'equal))
         (gptel-auto-workflow--research-status-cache '(1000 0 "stale"))
         (gptel-auto-workflow--research-status-ttl-seconds 5)
         (messages nil)
         (file-attribute-calls 0))
    (puthash project-root "abc" gptel-auto-workflow--research-findings-cache)
    (cl-letf (((symbol-function 'float-time)
               (let ((times '(1002.0 1003.0)))
                 (lambda (&optional _time)
                   (prog1 (car times)
                     (setq times (or (cdr times) times))))))
              ((symbol-function 'file-attributes)
               (lambda (&rest _args)
                 (cl-incf file-attribute-calls)
                 '(nil nil nil nil nil nil nil 42)))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (gptel-auto-workflow-research-status-all)
      (gptel-auto-workflow-research-status-all)
      (should (= file-attribute-calls 1))
      (should (consp gptel-auto-workflow--research-status-cache))
      (should (numberp (car gptel-auto-workflow--research-status-cache)))
      (should (stringp (cdr gptel-auto-workflow--research-status-cache)))
      (should (string-match-p "In-memory: 3 chars" (car messages)))
      (should (string-match-p "File: exists (42 bytes)" (car messages))))))

(ert-deftest regression/auto-workflow-projects/research-status-cache-reuses-valid-entry ()
  "Research status cache should reuse a fresh cached result."
  (let* ((project-root "/tmp/project-a")
         (gptel-auto-workflow-projects (list project-root))
         (gptel-auto-workflow--research-findings-cache (make-hash-table :test 'equal))
         (gptel-auto-workflow--research-status-cache nil)
         (gptel-auto-workflow--research-status-ttl-seconds 5)
         (messages nil)
         (file-attribute-calls 0))
    (puthash project-root "abcd" gptel-auto-workflow--research-findings-cache)
    (cl-letf (((symbol-function 'float-time)
               (let ((times '(1000.0 1002.0)))
                 (lambda (&optional _time)
                   (prog1 (car times)
                     (setq times (or (cdr times) times))))))
              ((symbol-function 'file-attributes)
               (lambda (&rest _args)
                 (cl-incf file-attribute-calls)
                 '(nil nil nil nil nil nil nil 24)))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (gptel-auto-workflow-research-status-all)
      (gptel-auto-workflow-research-status-all)
      (should (= file-attribute-calls 1))
      (should (equal (car messages)
                     (cadr messages)))
      (should (string-match-p "In-memory: 4 chars" (car messages))))))

(ert-deftest regression/auto-workflow-projects/run-all-projects-waits-for-async-completion ()
  "Project results should be recorded when async completion fires, not at start."
  (ert-skip "flaky in batch mode: test isolation issue with async callbacks")
  (let ((gptel-auto-workflow-projects '("/tmp/project-a" "/tmp/project-a"))
        (callbacks nil)
        (messages nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--get-project-buffer)
               (lambda (_root) (get-buffer-create "*aw-project*")))
              ((symbol-function 'hack-dir-local-variables-non-file-buffer)
               (lambda (&rest _) nil))
              ((symbol-function 'gptel-auto-workflow-cron-safe)
               (lambda (completion-callback)
                 (push completion-callback callbacks)
                 'started))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (gptel-auto-workflow-run-all-projects)
      (should (= (length callbacks) 1))
      (should-not (seq-some (lambda (msg)
                              (string-match-p "\\[auto-workflow\\] ✓ Completed:" msg))
                            messages))
      (funcall (car callbacks) '(:ok t))
      (should (seq-some (lambda (msg)
                          (string-match-p "\\[auto-workflow\\] ✓ Completed: /tmp/project-a/" msg))
                        messages))
      (should (seq-some (lambda (msg)
                          (string-match-p "\\[auto-workflow\\] All projects processed: /tmp/project-a/:success" msg))
                        messages)))))

(ert-deftest regression/auto-workflow-projects/run-all-projects-ignores-duplicate-completion ()
  "Late duplicate project completions should not re-log completion or finish twice."
  (ert-skip "flaky in batch mode: test isolation issue with async callbacks")
  (let ((gptel-auto-workflow-projects '("/tmp/project-a"))
        (callbacks nil)
        (messages nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow--get-project-buffer)
               (lambda (_root) (get-buffer-create "*aw-project*")))
              ((symbol-function 'hack-dir-local-variables-non-file-buffer)
               (lambda (&rest _) nil))
              ((symbol-function 'gptel-auto-workflow-cron-safe)
               (lambda (completion-callback)
                 (push completion-callback callbacks)
                 'started))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (gptel-auto-workflow-run-all-projects)
      (should (= (length callbacks) 1))
      (funcall (car callbacks) '(:ok t))
      (funcall (car callbacks) '(:ok t :duplicate t))
      (should (= (cl-count-if
                  (lambda (msg)
                    (string-match-p "\\[auto-workflow\\] ✓ Completed: /tmp/project-a/" msg))
                  messages)
                 1))
      (should (= (cl-count-if
                  (lambda (msg)
                    (string-match-p "\\[auto-workflow\\] All projects processed:" msg))
                  messages)
                 1)))))

(ert-deftest regression/auto-workflow-projects/run-instincts-for-project-binds-project-root ()
  "Instincts runs should bind project-root helpers to the requested project."
  (let* ((project-root (file-name-as-directory (make-temp-file "aw-instincts" t)))
         (gptel-auto-workflow--run-project-root "/tmp/stale")
         (captured-root nil)
         (enabled nil)
         (disabled nil))
    (unwind-protect
        (cl-letf (((symbol-function 'load-file)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--enable-headless-suppression)
                   (lambda () (setq enabled t)))
                  ((symbol-function 'gptel-auto-workflow--disable-headless-suppression)
                   (lambda () (setq disabled t)))
                  ((symbol-function 'gptel-benchmark-instincts-weekly-job)
                   (lambda ()
                     (setq captured-root (gptel-auto-workflow--project-root))))
                  ((symbol-function 'message)
                   (lambda (&rest _) nil)))
          (should (gptel-auto-workflow-run-instincts-for-project project-root))
          (should (equal captured-root project-root))
          (should enabled)
          (should disabled))
      (delete-directory project-root t))))

(ert-deftest regression/auto-workflow-projects/run-all-instincts-records-project-failures ()
  "Instincts summary should record failed projects as errors, not success."
  (let ((gptel-auto-workflow-projects '("/tmp/project-a"))
        (messages nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow-run-instincts-for-project)
               (lambda (_root) nil))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (should (equal (gptel-auto-workflow-run-all-instincts)
                     '(("/tmp/project-a" . error))))
      (should (seq-some (lambda (msg)
                          (string-match-p "\\[instincts\\] All projects processed: /tmp/project-a:error" msg))
                        messages))
      (should-not (seq-some (lambda (msg)
                              (string-match-p "/tmp/project-a:success" msg))
                            messages)))))

(ert-deftest regression/auto-workflow-projects/run-all-mementum-records-project-failures ()
  "Mementum summary should record failed projects as errors, not success."
  (let ((gptel-auto-workflow-projects '("/tmp/project-a"))
        (messages nil))
    (cl-letf (((symbol-function 'gptel-auto-workflow-run-mementum-for-project)
               (lambda (_root) nil))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (push (apply #'format fmt args) messages))))
      (should (equal (gptel-auto-workflow-run-all-mementum)
                     '(("/tmp/project-a" . error))))
      (should (seq-some (lambda (msg)
                          (string-match-p "\\[mementum\\] All projects processed: /tmp/project-a:error" msg))
                        messages))
      (should-not (seq-some (lambda (msg)
                              (string-match-p "/tmp/project-a:success" msg))
                            messages)))))

(provide 'test-gptel-auto-workflow-projects-regressions)

;;; test-gptel-auto-workflow-projects-regressions.el ends here
