;;; test-gptel-tools-agent-hydration-regressions.el --- Hydration regressions -*- lexical-binding: t; -*-

;;; Commentary:
;; Focused regressions for workflow submodule hydration edge cases.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'gptel-tools-agent)

(ert-deftest regression/auto-workflow/hydrate-staging-submodules-removes-stale-target-before-add ()
  "Hydration should remove a stale target dir before adding the submodule worktree."
  (let* ((root (make-temp-file "staging-root" t))
         (shared-git-dir (make-temp-file "shared-gptel" t))
         (target (expand-file-name "packages/gptel" root))
         saw-add)
    (unwind-protect
        (progn
          (make-directory target t)
          (with-temp-file (expand-file-name "stale.txt" target)
            (insert "stale"))
          (cl-letf (((symbol-function 'gptel-auto-workflow--staging-submodule-paths)
                     (lambda (&optional _worktree)
                       '("packages/gptel")))
                    ((symbol-function 'gptel-auto-workflow--staging-submodule-gitlink-revision)
                     (lambda (_worktree _path)
                       "abc123"))
                    ((symbol-function 'gptel-auto-workflow--shared-submodule-git-dir)
                     (lambda (_path &optional _commit)
                       shared-git-dir))
                    ((symbol-function 'gptel-auto-workflow--truncate-hash)
                     (lambda (commit)
                       commit))
                    ((symbol-function 'gptel-auto-workflow--git-result)
                     (lambda (command &optional _timeout)
                       (when (string-match-p "worktree add --detach --force" command)
                         (setq saw-add t)
                         (should-not (file-exists-p target)))
                       (cons "" 0))))
            (let ((delete-by-moving-to-trash t))
              (should (equal (gptel-auto-workflow--hydrate-staging-submodules root)
                             '("Hydrated submodules: packages/gptel=abc123" . 0))))
            (should saw-add)))
      (delete-directory root t)
      (delete-directory shared-git-dir t))))

(ert-deftest regression/auto-workflow/create-worktree-hydrates-empty-submodules ()
  "Experiment worktrees should hydrate empty top-level submodules before use."
  (let* ((proj-root (make-temp-file "workflow-root" t))
         (target "lisp/modules/example.el")
         (branch "optimize/example-exp1")
         (worktree-dir (expand-file-name (format "var/tmp/experiments/%s" branch) proj-root))
         (gptel-auto-workflow--worktree-state (make-hash-table :test #'equal))
         hydrated)
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow--worktree-base-root)
                   (lambda ()
                     proj-root))
                  ((symbol-function 'gptel-auto-workflow--branch-name)
                   (lambda (_target _experiment-id)
                     branch))
                  ((symbol-function 'gptel-auto-workflow--staging-main-ref)
                   (lambda ()
                     "origin/main"))
                  ((symbol-function 'gptel-auto-workflow--discard-worktree-buffers)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--branch-worktree-paths)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--worktree-needs-submodule-hydration-p)
                   (lambda (dir)
                     (equal dir worktree-dir)))
                  ((symbol-function 'gptel-auto-workflow--ensure-staging-submodules-ready)
                   (lambda (dir)
                     (setq hydrated dir)
                     t))
                  ((symbol-function 'call-process)
                   (lambda (program _in _buffer _display &rest args)
                     (when (and (equal program "git")
                                (equal args
                                       `("worktree" "add" "-b" ,branch
                                         ,worktree-dir "origin/main")))
                       (make-directory worktree-dir t))
                     0))
                  ((symbol-function 'message)
                   (lambda (&rest _) nil)))
          (should (equal (gptel-auto-workflow-create-worktree target 1)
                         worktree-dir))
          (should (equal hydrated worktree-dir)))
      (delete-directory proj-root t))))

(ert-deftest regression/auto-workflow/seed-worktree-runtime-var-links-shared-runtime-assets ()
  "Workflow worktrees should see ignored package/runtime assets from the stable root."
  (let* ((proj-root (make-temp-file "workflow-root" t))
         (worktree (expand-file-name "var/tmp/experiments/staging-verify" proj-root))
         (yaml-dir (expand-file-name "var/elpa/yaml-1.2.3" proj-root))
         (quickstart (expand-file-name "var/package-quickstart.el" proj-root))
         (treesit (expand-file-name "var/tree-sitter" proj-root)))
    (unwind-protect
        (progn
          (make-directory yaml-dir t)
          (with-temp-file (expand-file-name "yaml.el" yaml-dir)
            (insert ";;; yaml.el\n"))
          (with-temp-file quickstart
            (insert ";;; package quickstart\n"))
          (make-directory treesit t)
          (make-directory worktree t)
          (cl-letf (((symbol-function 'gptel-auto-workflow--worktree-base-repo-root)
                     (lambda () proj-root))
                    ((symbol-function 'gptel-auto-workflow--worktree-base-root)
                     (lambda () proj-root))
                    ((symbol-function 'message)
                     (lambda (&rest _) nil)))
            (should (gptel-auto-workflow--seed-worktree-runtime-var worktree)))
          (let ((linked-yaml (expand-file-name "var/elpa/yaml-1.2.3" worktree))
                (linked-quickstart (expand-file-name "var/package-quickstart.el" worktree))
                (linked-treesit (expand-file-name "var/tree-sitter" worktree)))
            (should (file-symlink-p linked-yaml))
            (should (equal (file-truename linked-yaml) (file-truename yaml-dir)))
            (should (file-symlink-p linked-quickstart))
            (should (equal (file-truename linked-quickstart) (file-truename quickstart)))
            (should (file-symlink-p linked-treesit))
            (should (equal (file-truename linked-treesit) (file-truename treesit)))))
      (delete-directory proj-root t))))

(ert-deftest regression/auto-workflow/create-staging-worktree-seeds-runtime-var ()
  "Staging verification worktrees should be hydrated before scripts run."
  (let* ((proj-root (make-temp-file "workflow-root" t))
         (gptel-auto-workflow--run-project-root proj-root)
         (seeded nil))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow--ensure-staging-branch-exists)
                   (lambda () t))
                  ((symbol-function 'gptel-auto-workflow--configured-staging-branch)
                   (lambda () "staging"))
                  ((symbol-function 'gptel-auto-workflow--discard-worktree-buffers)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--cleanup-staging-submodule-worktrees)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--git-cmd)
                   (lambda (&rest _) ""))
                  ((symbol-function 'gptel-auto-workflow--git-result)
                   (lambda (command &optional _timeout)
                     (when (string-match-p "git worktree add --force" command)
                       (make-directory (expand-file-name "var/tmp/experiments/staging-verify" proj-root) t))
                     (cons "" 0)))
                  ((symbol-function 'gptel-auto-workflow--seed-worktree-runtime-var)
                   (lambda (worktree)
                     (setq seeded worktree)
                     t))
                  ((symbol-function 'message)
                   (lambda (&rest _) nil)))
          (let ((worktree (gptel-auto-workflow--create-staging-worktree)))
            (should (equal worktree
                           (expand-file-name "var/tmp/experiments/staging-verify" proj-root)))
            (should (equal seeded worktree))))
      (delete-directory proj-root t))))

(ert-deftest regression/auto-workflow/temporary-worktree-seeds-runtime-var ()
  "Main-baseline verification worktrees should be hydrated before callbacks run."
  (let* ((proj-root (make-temp-file "workflow-root" t))
         (worktree (expand-file-name "var/tmp/experiments/main-baseline-123" proj-root))
         (called nil)
         (seeded nil))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow--default-dir)
                   (lambda () proj-root))
                  ((symbol-function 'gptel-auto-workflow--temporary-worktree-path)
                   (lambda (_slug) worktree))
                  ((symbol-function 'gptel-auto-workflow--git-cmd)
                   (lambda (&rest _) ""))
                  ((symbol-function 'gptel-auto-workflow--git-result)
                   (lambda (command &optional _timeout)
                     (when (string-match-p "git worktree add --force --detach" command)
                       (make-directory worktree t))
                     (cons "" 0)))
                  ((symbol-function 'gptel-auto-workflow--cleanup-staging-submodule-worktrees)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--seed-worktree-runtime-var)
                   (lambda (dir)
                     (setq seeded dir)
                     t))
                  ((symbol-function 'message)
                   (lambda (&rest _) nil)))
          (gptel-auto-workflow--with-temporary-worktree
           "main-baseline"
           "main"
           (lambda (dir)
             (setq called dir)))
          (should (equal called worktree))
          (should (equal seeded worktree)))
      (when (file-exists-p proj-root)
        (delete-directory proj-root t)))))

(ert-deftest regression/auto-workflow/create-worktree-fails-when-submodule-hydration-fails ()
  "Experiment worktree creation should stop before executor use when hydration fails."
  (let* ((proj-root (make-temp-file "workflow-root" t))
         (target "lisp/modules/example.el")
         (branch "optimize/example-exp1")
         (worktree-dir (expand-file-name (format "var/tmp/experiments/%s" branch) proj-root))
         (gptel-auto-workflow--worktree-state (make-hash-table :test #'equal)))
    (unwind-protect
        (cl-letf (((symbol-function 'gptel-auto-workflow--worktree-base-root)
                   (lambda ()
                     proj-root))
                  ((symbol-function 'gptel-auto-workflow--branch-name)
                   (lambda (_target _experiment-id)
                     branch))
                  ((symbol-function 'gptel-auto-workflow--staging-main-ref)
                   (lambda ()
                     "origin/main"))
                  ((symbol-function 'gptel-auto-workflow--discard-worktree-buffers)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--branch-worktree-paths)
                   (lambda (&rest _) nil))
                  ((symbol-function 'gptel-auto-workflow--worktree-needs-submodule-hydration-p)
                   (lambda (dir)
                     (equal dir worktree-dir)))
                  ((symbol-function 'gptel-auto-workflow--ensure-staging-submodules-ready)
                   (lambda (_dir)
                     nil))
                  ((symbol-function 'call-process)
                   (lambda (program _in _buffer _display &rest args)
                     (when (and (equal program "git")
                                (equal args
                                       `("worktree" "add" "-b" ,branch
                                         ,worktree-dir "origin/main")))
                       (make-directory worktree-dir t))
                     0))
                  ((symbol-function 'message)
                   (lambda (&rest _) nil)))
          (should-not (gptel-auto-workflow-create-worktree target 1))
          (should-not (plist-get (gethash target gptel-auto-workflow--worktree-state)
                                 :worktree-dir))
          (should-not (plist-get (gethash target gptel-auto-workflow--worktree-state)
                                 :current-branch)))
      (delete-directory proj-root t))))

;;; test-gptel-tools-agent-hydration-regressions.el ends here
