;;; test-evolution-timeout.el --- TDD: evolution cycle timeout guard -*- lexical-binding: t; -*-

;; Verifies that `gptel-auto-workflow-evolution-run-cycle' returns within
;; the timeout even when a sub-function blocks indefinitely.

;;; Code:

(require 'ert)
(require 'cl-lib)

;; Load evolution module (minimal: just the function we test)
(unless (featurep 'gptel-auto-workflow-evolution)
  (load (expand-file-name "lisp/modules/gptel-auto-workflow-evolution.el"
                          default-directory)))

(ert-deftest tdd/evolution-run-cycle/respects-timeout ()
  "When a sub-function blocks, evolution-run-cycle returns within timeout."
  ;; Mock a normally-fast function to block for 10s
  (cl-letf (((symbol-function 'gptel-auto-workflow--build-digital-twin)
             (lambda (&optional _) (sit-for 10))))
    (let ((start (float-time))
          (result (gptel-auto-workflow-evolution-run-cycle 2)))
      (let ((elapsed (- (float-time) start)))
        ;; Must return within 3s (2s timeout + 1s margin)
        (should (< elapsed 3))
        ;; Must return the timeout sentinel, not hang forever
        (should (string= result "timeout"))))))

(ert-deftest tdd/evolution-run-cycle/fast-path-unaffected ()
  "When no blocking, evolution-run-cycle returns quickly with normal result."
  (cl-letf (((symbol-function 'gptel-auto-workflow--build-digital-twin)
             (lambda (&optional _) nil))
            ;; Stub out expensive steps so test is fast
            ((symbol-function 'gptel-auto-workflow--restore-next-cycle-hints)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--eight-keys-convergence-score)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--validate-pipeline)
             (lambda () (list :valid t :errors nil :warnings nil)))
            ((symbol-function 'gptel-auto-workflow--evolution-count-new)
             (lambda () 0))
            ((symbol-function 'gptel-auto-workflow--monitoring-cycle)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-synthesize)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-consolidate-insights)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolve-all-skills)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-record-score)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-optimize-backend-order)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-persist-backend-comparison)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-persist-model-comparison)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--allium-trends-report)
             (lambda () ""))
            ((symbol-function 'gptel-auto-workflow--allium-save-regression-baseline)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evolution-vsm-health-check)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--classify-experiment-impact)
             (lambda () (list :summary (list :total 0 :breaking 0 :potentially-breaking 0 :safe 0))))
            ((symbol-function 'gptel-auto-workflow--check-competency-questions)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--gate-strategies)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--apply-cross-subsystem-feedback)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--decay-category-strikes)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--consume-vsm-actions)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--check-all-targets-consistency)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--filter-by-ambiguity)
             (lambda (_ _ ) nil))
            ((symbol-function 'gptel-auto-workflow--second-chance-repair)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--check-policy)
             (lambda (_ _ ) (list :valid t :errors nil :warnings nil)))
            ((symbol-function 'gptel-auto-workflow--audit-signal)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--allium-audit-signal)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--allium-bdd-gate)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--allium-diff-minimal-pairs)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--write-research-priorities)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--enrich-ontology-from-research)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--queue-research-pair-probes)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--diff-knowledge-pages)
             (lambda () (list :added nil :removed nil :changed nil)))
            ((symbol-function 'gptel-auto-workflow--validate-knowledge-page)
             (lambda (_) (list :valid t :errors nil :warnings nil)))
            ((symbol-function 'gptel-auto-workflow--forward-chain)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--abductive-diagnose)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--deductive-explain)
             (lambda (_) nil))
            ((symbol-function 'gptel-auto-workflow--datalog-transitive-chain)
             (lambda (_) nil))
            ((symbol-function 'gptel-auto-workflow--experiment-time-gaps)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--memory-status)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--evaluate-holdout)
             (lambda () (list :average 0.0 :trend 0.0)))
            ((symbol-function 'gptel-auto-workflow--produce-candidates-for-llm)
             (lambda (_) nil))
            ((symbol-function 'gptel-auto-workflow--build-inverted-file)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--overall-keep-rate)
             (lambda () 0.0))
            ((symbol-function 'gptel-auto-workflow--total-experiments)
             (lambda () 0))
            ((symbol-function 'gptel-auto-workflow-operational-metrics-report)
             (lambda () nil))
            ((symbol-function 'gptel-auto-workflow--emit-result)
             (lambda (&rest _) nil))
            ((symbol-function 'gptel-auto-workflow--autoresearch-check)
             (lambda (_) nil)))
    (let ((start (float-time))
          (result (gptel-auto-workflow-evolution-run-cycle 5)))
      (let ((elapsed (- (float-time) start)))
        ;; Must return within 5 seconds (all stubs are fast)
        (should (< elapsed 5))
        ;; Should NOT be a timeout (all stubs return instantly)
        (should-not (string= result "timeout"))))))

(provide 'test-evolution-timeout)
;;; test-evolution-timeout.el ends here
