#!/usr/bin/env bash
# detect-patterns.sh — Scan pipeline logs, detect patterns, auto-generate knowledge

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_FILE="$DIR/mementum/.pipeline-log"
PATTERNS_DIR="$DIR/mementum/knowledge/patterns"
THRESHOLD=3

[ -f "$LOG_FILE" ] || { echo "No pipeline log found"; exit 0; }

mkdir -p "$PATTERNS_DIR"

# Count occurrences of known patterns
count_pattern() {
    local keyword="$1"
    grep -c "$keyword" "$LOG_FILE" 2>/dev/null || echo 0
}

echo "=== Pattern Detection ==="
echo ""

# Known patterns
declare -A PATTERNS
PATTERNS=(
    ["Pi5 auto-evolves"]=$(count_pattern "merge=theirs")
    ["python3 regression"]=$(count_pattern "python3")
    ["Hardcoded paths"]=$(count_pattern "main-baseline-")
    ["defvar at top-level"]=$(count_pattern "defvar")
    ["byte-compile warning"]=$(count_pattern "byte-compile")
    ["submodule sync"]=$(count_pattern "submodule")
)

for pattern in "${!PATTERNS[@]}"; do
    count="${PATTERNS[$pattern]}"
    if [ "$count" -ge "$THRESHOLD" ]; then
        echo "PATTERN: $pattern ($count occurrences) → candidate for knowledge page"
    fi
done

echo ""
echo "=== Knowledge Page Candidates ==="

for pattern in "${!PATTERNS[@]}"; do
    count="${PATTERNS[$pattern]}"
    if [ "$count" -ge "$THRESHOLD" ]; then
        slug=$(echo "$pattern" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')
        page="$PATTERNS_DIR/$slug.md"
        if [ ! -f "$page" ]; then
            echo "  Creating: $page ($count occurrences)"
            cat > "$page" <<EOF
# $pattern

> **Synthesized**: $(date '+%Y-%m-%d')
> **Occurrences**: $count

## Description

Auto-detected pattern from pipeline logs.

## Occurrences

$(grep "$pattern" "$LOG_FILE" 2>/dev/null | tail -5 | sed 's/^/ - /')

## Resolution

TODO: Add resolution steps.

## Prevention

TODO: Add prevention strategies.

---
*Auto-generated by detect-patterns.sh*
EOF
        else
            echo "  Already exists: $page"
        fi
    fi
done

echo ""
echo "Done. Knowledge pages: $PATTERNS_DIR"
