#!/usr/bin/env bash
# ov5-project-init.sh — Bootstrap a new OV5-managed Clojure project
# Usage: ./scripts/ov5-project-init.sh <project-dir> <project-name>
#
# Creates a complete OV5-managed project with:
#   - Clojure toolchain (bb.edn, deps.edn)
#   - OV5 target config (.dir-locals.el)
#   - CI pipeline (scripts/run-tests.sh)
#   - OpenCode config (.opencode/)
#   - Mementum memory (mementum/)
#   - AI agent bootstrap (AGENTS.md)
#   - Registration in OV5's post-init.el
#
# Example:
#   ./scripts/ov5-project-init.sh ~/workspace/creatoros "CreatorOS"

set -euo pipefail

PROJECT_DIR="${1:-}"
PROJECT_NAME="${2:-$(basename "${1:-}")}"
OV5_DIR="${OV5_DIR:-$HOME/.emacs.d}"
SCRIPT_NAME="$(basename "$0")"

if [ -z "$PROJECT_DIR" ]; then
    echo "Usage: $SCRIPT_NAME <project-dir> [project-name]"
    echo "Example: $SCRIPT_NAME ~/workspace/myapp \"My App\""
    exit 1
fi

PROJECT_DIR="$(cd "$PROJECT_DIR" 2>/dev/null && pwd || echo "$PROJECT_DIR")"

echo "=== OV5 Project Init: $PROJECT_NAME ==="
echo "Project: $PROJECT_DIR"
echo "OV5:     $OV5_DIR"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# Step 1: Create directory structure
# ═══════════════════════════════════════════════════════════════════════════
echo "[1/8] Creating directory structure..."
mkdir -p "$PROJECT_DIR"/{src,test,scripts,docs,extension,mementum/{memories,knowledge}}
mkdir -p "$PROJECT_DIR/.opencode"/{skills,agents}
echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 2: Clojure project files
# ═══════════════════════════════════════════════════════════════════════════
echo "[2/8] Creating Clojure project files..."

cat > "$PROJECT_DIR/bb.edn" <<'BBEDN'
{:paths ["src" "test"]}
BBEDN

cat > "$PROJECT_DIR/deps.edn" <<'DEPSEDN'
{:paths ["src" "test"]
 :deps {}
 :aliases
 {:test {:extra-paths ["test"]
         :extra-deps {org.clojure/clojure {:mvn/version "1.12.0"}
                      org.clojure/test.check {:mvn/version "1.1.1"}}}}}
DEPSEDN

cat > "$PROJECT_DIR/.gitignore" <<'GITIGNORE'
target/
.classpath
.project
.settings
*.iml
*.ipr
*.iws
.idea/
.lsp/
.clj-kondo/.cache/
*.class
*.jar
node_modules/
.cpcache/
.DS_Store
GITIGNORE

echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 3: OV5 target config
# ═══════════════════════════════════════════════════════════════════════════
echo "[3/8] Creating OV5 target config (.dir-locals.el)..."

SOURCE_FILES=$(ls "$PROJECT_DIR/src"/*.clj 2>/dev/null | sed "s|$PROJECT_DIR/||g" | sed 's/^/"/;s/$/"/' | tr '\n' ' ')
if [ -z "$SOURCE_FILES" ]; then
    SOURCE_FILES='"src/example.clj" "src/utils.clj"'
fi

cat > "$PROJECT_DIR/.dir-locals.el" <<DIRLOCALS
;;; .dir-locals.el — $PROJECT_NAME auto-workflow configuration
;; Generated by $SCRIPT_NAME on $(date +%Y-%m-%d)
;; See OV5: $OV5_DIR/lisp/modules/gptel-auto-workflow-projects.el

((nil
  . ((gptel-auto-workflow-targets
      . ($SOURCE_FILES))
     (gptel-auto-experiment-max-per-target . 2)
     (gptel-auto-experiment-time-budget . 600)
     (gptel-auto-experiment-no-improvement-threshold . 3))))
DIRLOCALS

echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 4: CI pipeline
# ═══════════════════════════════════════════════════════════════════════════
echo "[4/8] Creating CI pipeline (scripts/run-tests.sh)..."

cat > "$PROJECT_DIR/scripts/run-tests.sh" <<'TESTSCRIPT'
#!/usr/bin/env bash
# OV5-compatible test runner for Clojure projects
# Usage: ./scripts/run-tests.sh [unit|clj|all]
# OV5 calls with "unit" argument — we run everything.

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
FAILED=0

echo "=== ${DIR##*/} Tests ==="

echo -n "Lint (clj-kondo)... "
if clj-kondo --lint src/ test/ 2>&1 | grep -q "error:"; then
    echo -e "${RED}FAIL${NC}"
    FAILED=1
else
    echo -e "${GREEN}PASS${NC}"
fi

echo -n "Format (zprint)... "
if command -v zprint &>/dev/null; then
    for f in src/*.clj test/*.clj 2>/dev/null; do
        [ -f "$f" ] || continue
        if ! zprint "$f" | diff - "$f" >/dev/null 2>&1; then
            echo -e "${RED}FAIL${NC} ($f)"
            FAILED=1
            break
        fi
    done
    [ $FAILED -eq 0 ] && echo -e "${GREEN}PASS${NC}"
else
    echo -e "${GREEN}SKIP${NC} (zprint not installed)"
fi

echo -n "Test (bb)... "
BB_OUT=$(bb -cp src:test -e '
(require (quote clojure.test))
(let [ns-pattern #".*_test\.clj$"
      test-files (->> (clojure.java.io/file "test")
                      file-seq
                      (filter #(and (.isFile %) (re-find ns-pattern (.getPath %))))
                      (sort))
      loaded (atom [])]
  (if (empty? test-files)
    (do (println "No tests found") (System/exit 0))
    (do
      (doseq [f test-files]
        (let [ns-sym (-> (.getPath f)
                         (clojure.string/replace #"^test/" "")
                         (clojure.string/replace #"/" ".")
                         (clojure.string/replace #"_" "-")
                         (clojure.string/replace #"\.clj$" "")
                         (symbol))]
          (try (require ns-sym) (swap! loaded conj ns-sym)
            (catch Exception e (println "ERROR:" (.getMessage e))))))
      (if (empty? @loaded)
        (do (println "No tests loaded") (System/exit 1))
        (let [results (apply clojure.test/run-tests @loaded)
              total (+ (:pass results) (:fail results) (:error results))]
          (println (str "Ran " total " tests. " (:fail results) " failures, " (:error results) " errors."))
          (System/exit (if (zero? (+ (:fail results) (:error results))) 0 1)))))))' 2>&1
BB_EXIT=$?
if [ $BB_EXIT -eq 0 ]; then
    echo -e "${GREEN}PASS${NC}"
else
    echo -e "${RED}FAIL${NC}"
    echo "$BB_OUT"
    FAILED=1
fi

if [ $FAILED -ne 0 ]; then
    echo -e "\n${RED}Tests failed.${NC}"
    exit 1
fi
echo -e "\n${GREEN}All checks passed.${NC}"
exit 0
TESTSCRIPT

chmod +x "$PROJECT_DIR/scripts/run-tests.sh"
echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 5: OpenCode config
# ═══════════════════════════════════════════════════════════════════════════
echo "[5/8] Creating OpenCode config..."

cat > "$PROJECT_DIR/.opencode/config.jsonc" <<OPENC
{
  "\$schema": "https://opencode.ai/config.json",
  "project": {
    "name": "$PROJECT_NAME",
    "language": "clojure"
  },
  "tools": {
    "permissions": {
      "bash": {
        "allow": [
          "bb -cp src:test -e *",
          "clj-kondo --lint *",
          "zprint *",
          "./scripts/run-tests.sh *",
          "git *"
        ]
      },
      "edit": { "allow": ["src/**", "test/**", "*.md"] },
      "write": { "allow": ["src/**", "test/**", "*.md"] },
      "read": { "allow": ["**"] }
    }
  },
  "skills": {
    "load": [
      "daemon-repl",
      "brepl",
      "creatoros",
      ".opencode/skills/ov5/SKILL.md"
    ]
  },
  "context": {
    "ov5": {
      "path": "$OV5_DIR",
      "description": "OV5 self-improving AI system"
    }
  }
}
OPENC

mkdir -p "$PROJECT_DIR/.opencode/skills/ov5"
cat > "$PROJECT_DIR/.opencode/skills/ov5/SKILL.md" <<'OV5SKILL'
# Skill: ov5

OV5 is the self-improving AI system that manages this project from ~/.emacs.d.

## What OV5 Does

Runs autonomous experiments on project code: selects targets, generates hypotheses, runs tests (lint + format + test), keeps winners (20% keep-rate), learns from discards.

## Development Workflow

1. Write code in src/
2. Run ./scripts/run-tests.sh (lint + format + test)
3. Commit and push
4. OV5 picks up changes, runs experiments overnight
5. Morning: review kept experiments

## Quality Gates

| Gate | Command |
|------|---------|
| Lint | clj-kondo --lint src/ test/ |
| Format | zprint |
| Test | ./scripts/run-tests.sh |

## References

- OV5 repo: ~/.emacs.d
- Architecture: ~/.emacs.d/OUROBOROS-V5.md
- Clojure strategy: ~/.emacs.d/mementum/knowledge/clojure-first-multiplatform-architecture.md
OV5SKILL

echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 6: Mementum memory
# ═══════════════════════════════════════════════════════════════════════════
echo "[6/8] Creating mementum memory..."

cat > "$PROJECT_DIR/mementum/state.md" <<MEM
# $PROJECT_NAME — Working Memory

> **Created**: $(date +%Y-%m-%d)
> **Status**: ✅ Initialized — OV5-managed Clojure project
> **OV5**: Managing via experiment loop at \`$OV5_DIR\`

## Current State

| Component | Status |
|-----------|--------|
| Project scaffold | ✅ |
| CI Pipeline | ✅ |
| OV5 Integration | ✅ |
| OpenCode Config | ✅ |

## Key Decisions

1. Clojure-first — one language, 39 dialect targets, every platform.
2. OV5-managed — experiments run autonomously, human reviews 15 min/day.
3. Flat SaaS pricing — no revenue share, pay for intelligence.

## OV5 Experiment Loop

- Test gate: \`scripts/run-tests.sh unit\`
- Lint gate: \`clj-kondo --lint src/ test/\`
- Format gate: \`zprint\`
- Self-heal: ns-ordering, unused-require removal
MEM

echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 7: AGENTS.md bootstrap
# ═══════════════════════════════════════════════════════════════════════════
echo "[7/8] Creating AGENTS.md..."

cat > "$PROJECT_DIR/AGENTS.md" <<AGENTS
# AGENTS.md — $PROJECT_NAME

> OV5-managed Clojure project. Product intelligence engine.

## Quick Start

\`\`\`bash
./scripts/run-tests.sh    # Lint + format + test
bb -cp src:test -e '...'  # REPL eval
\`\`\`

## Quality Gates

| Gate | Command |
|------|---------|
| Lint | \`clj-kondo --lint src/ test/\` |
| Format | \`zprint\` |
| Test | \`./scripts/run-tests.sh\` |

**Always run \`./scripts/run-tests.sh\` before committing.**

## OV5 Workflow

This project is managed by [OV5]($OV5_DIR). The experiment loop runs 100+ experiments/month.

1. Write code → \`./scripts/run-tests.sh\` → commit
2. OV5 experiments overnight
3. Review kept experiments in morning

## Self-Regulation

| Layer | This Project Owns | OV5 Enables |
|-------|-------------------|-------------|
| Sensor | Data sources, accuracy | OV5 monitoring |
| Policy | Risk thresholds | Experiment config |
| Tools | Engine code | Toolchain (test/lint/format) |
| Quality Gate | 3 gates | \`scripts/run-tests.sh\` |
| Learning | Keep-rate | 100+ experiments/month |

## Key Files

| File | Purpose |
|------|---------|
| \`.opencode/config.jsonc\` | OpenCode project config |
| \`.dir-locals.el\` | OV5 target configuration |
| \`mementum/state.md\` | Working memory |
| \`docs/\` | Architecture and product docs |
AGENTS

echo "  ✅ Done"

# ═══════════════════════════════════════════════════════════════════════════
# Step 8: Register in OV5
# ═══════════════════════════════════════════════════════════════════════════
echo "[8/8] Registering in OV5 (post-init.el)..."

PROJECT_DIR_FULL="$(cd "$PROJECT_DIR" && pwd)"
POST_INIT="$OV5_DIR/post-init.el"

if [ -f "$POST_INIT" ]; then
    if ! grep -q "$PROJECT_DIR_FULL" "$POST_INIT" 2>/dev/null; then
        BLOCK=$(cat <<REGISTER
;; --- Auto-workflow: $PROJECT_NAME ($(date +%Y-%m-%d)) ---
(with-eval-after-load 'gptel-auto-workflow-projects
  (let ((proot (expand-file-name "$PROJECT_DIR_FULL/")))
    (when (file-directory-p proot)
      (add-to-list 'gptel-auto-workflow-projects (directory-file-name proot))
      (add-to-list 'gptel-auto-workflow--allowed-workspace-roots proot))))
REGISTER
)
        echo "$BLOCK" >> "$POST_INIT"
        echo "  ✅ Registered in OV5 post-init.el"
    else
        echo "  ⏭️  Already registered"
    fi
else
    echo "  ⚠️  OV5 post-init.el not found at $POST_INIT"
    echo "  Add manually: (add-to-list 'gptel-auto-workflow-projects \"$PROJECT_DIR_FULL\")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════════════
echo ""
echo "=== $PROJECT_NAME initialized ==="
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_DIR"
echo "  2. Write your first module: src/$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')/core.clj"
echo "  3. Write tests: test/$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')/core_test.clj"
echo "  4. Run: ./scripts/run-tests.sh"
echo "  5. git init && git add -A && git commit -m 'Initial scaffold'"
echo "  6. Restart Emacs daemon for OV5 to discover the project"
echo ""
echo "OV5 will now run experiments on this project automatically."
