;; Auto-evolved per-axis backend preference
;; Updated: 2026-06-07 — TokenPlan preferred (DeepSeek/Kimi quota exhausted)
(setq gptel-auto-workflow--task-backend-preference
      '(("analyzer" "TokenPlan" . 0.40)
        ("executor" "TokenPlan" . 0.40)
        ("grader" "TokenPlan" . 0.40)
        ("researcher" "TokenPlan" . 0.40)
        ("reviewer" "TokenPlan" . 0.40)
        ("comparator" "TokenPlan" . 0.40)
        ("analyzer" "MiniMax" . 0.30)
        ("executor" "MiniMax" . 0.30)
        ("grader" "MiniMax" . 0.30)
        ("researcher" "MiniMax" . 0.30)
        ("reviewer" "MiniMax" . 0.30)
        ("comparator" "MiniMax" . 0.30)
        ("analyzer" "DashScope" . 0.20)
        ("executor" "DashScope" . 0.20)
        ("grader" "DashScope" . 0.20)
        ("researcher" "DashScope" . 0.20)
        ("reviewer" "DashScope" . 0.20)
        ("comparator" "DashScope" . 0.20)
        ("analyzer" "DeepSeek" . 0.10)
        ("executor" "DeepSeek" . 0.10)
        ("grader" "DeepSeek" . 0.10)
        ("researcher" "DeepSeek" . 0.10)
        ("reviewer" "DeepSeek" . 0.10)
        ("comparator" "DeepSeek" . 0.10)))
