;;; gptel-auto-workflow-mementum.el --- Integrate auto-workflow with mementum -*- lexical-binding: t -*-

;; This module bridges auto-workflow experiments with the mementum memory system.
;; It creates atomic memories per experiment and synthesizes them into knowledge pages.
;;
;; Data flow:
;;   Experiment results ──→ Memories ──→ Knowledge synthesis ──→ Prompt injection
;;        ↓                    ↓              ↓                      ↓
;;     TSV + Git         mementum/      Weekly batch          Executor +
;;                        memories/      job updates           Analyzer
;;                                      knowledge/

(require 'cl-lib)
(require 'subr-x)

;; ─── Configuration ───

(defcustom gptel-auto-workflow-mementum-enabled t
  "When non-nil, write experiment results to mementum."
  :type 'boolean
  :group 'gptel-tools-agent)

(defcustom gptel-auto-workflow-mementum-dir "mementum"
  "Base directory for mementum memories and knowledge."
  :type 'directory
  :group 'gptel-tools-agent)

(defcustom gptel-auto-workflow-mementum-memory-dir "mementum/memories"
  "Directory for atomic memory files."
  :type 'directory
  :group 'gptel-tools-agent)

(defcustom gptel-auto-workflow-mementum-knowledge-dir "mementum/knowledge"
  "Directory for synthesized knowledge pages."
  :type 'directory
  :group 'gptel-tools-agent)

;; ─── Memory Creation ───

(defvar gptel-auto-workflow--mementum-symbol-map
  '((💡 . "insight")
    (❌ . "mistake")
    (✅ . "win")
    (🔄 . "shift")
    (🎯 . "decision"))
  "Alist mapping emoji symbols to kebab-case filename prefixes.")

(defun gptel-auto-workflow--mementum-symbol-prefix (symbol)
  "Return kebab-case prefix for SYMBOL."
  (or (cdr (assq symbol gptel-auto-workflow--mementum-symbol-map))
      "memory"))

(defun gptel-auto-workflow--mementum-slug (text)
  "Generate a URL-safe slug from TEXT."
  (let* ((clean (replace-regexp-in-string "[^a-zA-Z0-9]" "-" text))
         (collapsed (replace-regexp-in-string "-+" "-" clean))
         (slug (downcase (string-trim collapsed "-"))))
    (substring slug 0 (min 80 (length slug)))))

(defun gptel-auto-workflow--mementum-write-memory (symbol slug content)
  "Write a memory file with SYMBOL prefix and SLUG.
CONTENT is the body text."
  (let* ((dir (expand-file-name gptel-auto-workflow-mementum-memory-dir
                                (gptel-auto-workflow--worktree-base-root)))
         (prefix (gptel-auto-workflow--mementum-symbol-prefix symbol))
         (file (expand-file-name (format "%s-%s.md" prefix slug) dir)))
    (make-directory dir t)
    (with-temp-file file
      (insert (format "# %s %s\n\n%s\n\n---\n*Generated by auto-workflow*\n"
                      (pcase symbol
                        ('💡 "Insight:")
                        ('❌ "Mistake:")
                        ('✅ "Win:")
                        ('🔄 "Shift:")
                        ('🎯 "Decision:"))
                      (format-time-string "%Y-%m-%d %H:%M")
                      content)))
    file))

(defun gptel-auto-workflow--mementum-record-experiment (experiment)
  "Record EXPERIMENT result to mementum.
EXPERIMENT is a plist with :target :hypothesis :score-before :score-after
:code-quality :decision :grader-quality :grader-reason."
  (when gptel-auto-workflow-mementum-enabled
    (let* ((target (plist-get experiment :target))
           (hypothesis (plist-get experiment :hypothesis))
           (decision (plist-get experiment :decision))
           (score-before (plist-get experiment :score-before))
           (score-after (plist-get experiment :score-after))
           (quality (plist-get experiment :code-quality))
           (grader-q (plist-get experiment :grader-quality))
           (change-type (gptel-auto-workflow--categorize-hypothesis hypothesis))
           (slug (gptel-auto-workflow--mementum-slug
                  (format "%s-%s" target hypothesis))))
      (pcase decision
        ("kept"
         (gptel-auto-workflow--mementum-write-memory
          '✅ slug
          (format "**Target:** %s\n**Change type:** %s\n**Hypothesis:** %s\n**Score:** %.2f → %.2f\n**Quality:** %.2f\n**Grader:** %d/9\n\nThis change was kept because it improved the combined score or had significant quality gains."
                  target change-type hypothesis score-before score-after quality grader-q)))
        ("discarded"
         (gptel-auto-workflow--mementum-write-memory
          '❌ slug
          (format "**Target:** %s\n**Change type:** %s\n**Hypothesis:** %s\n**Score:** %.2f → %.2f\n**Quality:** %.2f\n**Grader:** %d/9\n\nThis change was discarded. Score tie without sufficient quality gain, or regression."
                  target change-type hypothesis score-before score-after quality grader-q)))
        ("timeout"
         (gptel-auto-workflow--mementum-write-memory
          '❌ slug
          (format "**Target:** %s\n**Hypothesis:** %s\n**Result:** TIMEOUT\n\nExperiment timed out. Consider reducing scope or increasing time budget for this target."
                  target hypothesis)))
        ("grader-rejected"
         (gptel-auto-workflow--mementum-write-memory
          '❌ slug
          (format "**Target:** %s\n**Hypothesis:** %s\n**Result:** GRADER REJECTED\n**Grader:** %d/9\n\nChange failed grader review. Hypothesis did not match actual changes, or change was too large/unsafe."
                  target hypothesis grader-q)))
        (_
         (gptel-auto-workflow--mementum-write-memory
          '💡 slug
          (format "**Target:** %s\n**Change type:** %s\n**Hypothesis:** %s\n**Decision:** %s\n\nUnexpected experiment outcome."
                  target change-type hypothesis decision)))))))

;; ─── Knowledge Synthesis ───

(defun gptel-auto-workflow--mementum-read-memories (days)
  "Read memories from the last N DAYS.
Returns list of (file-path . content) cons cells."
  (let* ((dir (expand-file-name gptel-auto-workflow-mementum-memory-dir
                                (gptel-auto-workflow--worktree-base-root)))
         (cutoff (time-subtract (current-time) (days-to-time days)))
         (memories nil))
    (when (file-directory-p dir)
      (dolist (file (directory-files dir t "\\.md$"))
        (let ((mtime (file-attribute-modification-time
                      (file-attributes file))))
          (when (time-less-p cutoff mtime)
            (push (cons file
                        (with-temp-buffer
                          (insert-file-contents file)
                          (buffer-string)))
                  memories)))))
    (nreverse memories)))

(defun gptel-auto-workflow--mementum-synthesize-knowledge ()
  "Synthesize recent memories into knowledge pages.
Updates auto-workflow-evolution.md with patterns from recent experiments."
  (when gptel-auto-workflow-mementum-enabled
    (let* ((memories (gptel-auto-workflow--mementum-read-memories 7))
           (knowledge-dir (expand-file-name gptel-auto-workflow-mementum-knowledge-dir
                                            (gptel-auto-workflow--worktree-base-root)))
           (knowledge-file (expand-file-name "auto-workflow-evolution.md" knowledge-dir))
            ;; Get git stats for synthesis
            (git-commits (gptel-auto-workflow--git-experiment-commits))
           (target-stats (gptel-auto-workflow--git-compute-target-stats git-commits))
           (category-stats (gptel-auto-workflow--git-compute-category-stats git-commits)))

      (make-directory knowledge-dir t)

      ;; Build knowledge content
      (with-temp-file knowledge-file
        (insert "---\n")
        (insert "title: Auto-Workflow Evolution Patterns\n")
        (insert (format "status: active\n"))
        (insert "category: knowledge\n")
        (insert "tags: [auto-workflow, benchmark, evolution, patterns]\n")
        (insert (format "updated: %s\n" (format-time-string "%Y-%m-%d %H:%M")))
        (insert "---\n\n")

        (insert "# Auto-Workflow Evolution Patterns\n\n")
        (insert "*This page is automatically synthesized from experiment results and git history.*\n\n")

        ;; Section 1: Success Patterns by Change Type
        (insert "## Change Type Success Rates\n\n")
        (insert "Based on merged experiment commits (git history):\n\n")
        (dolist (stat category-stats)
          (let* ((cat (nth 0 stat))
                 (total (nth 1 stat))
                 (kept (nth 2 stat))
                 (rate (nth 3 stat))
                 (cat-name (pcase cat
                             ('bug-fix "Bug fixes / error handling")
                             ('performance "Performance improvements")
                             ('refactoring "Refactoring / deduplication")
                             ('safety "Safety / defensive checks")
                             ('feature "New features / enhancements")
                             ('other "Other changes"))))
            (when (> total 0)
              (insert (format "- **%s**: %.0f%% (%d/%d commits)\n"
                              cat-name (* 100 rate) kept total)))))
        (insert "\n")

        ;; Section 2: Target File Patterns
        (insert "## Target File Success Rates\n\n")
        (insert "Files ranked by experiment merge rate:\n\n")
        (dolist (stat target-stats)
          (let* ((target (nth 0 stat))
                 (total (nth 1 stat))
                 (kept (nth 2 stat))
                 (rate (nth 3 stat)))
            (insert (format "- `%s`: %.0f%% (%d/%d experiments)\n"
                            target (* 100 rate) kept total))))
        (insert "\n")

        ;; Section 3: Recent Memories
        (insert "## Recent Experiment Memories\n\n")
        (insert (format "*%d memories from last 7 days:*\n\n" (length memories)))
        (dolist (mem (seq-take memories 10))
          (let* ((file (car mem))
                 (content (cdr mem))
                 (filename (file-name-nondirectory file)))
            (insert (format "### %s\n\n" filename))
            (insert content)
            (insert "\n")))

        ;; Section 4: Recommendations
        (insert "## Recommendations for Next Experiments\n\n")
        (insert "Based on pattern analysis:\n\n")
        ;; Find best target
        (when target-stats
          (let ((best-target (car target-stats)))
            (insert (format "- **Prioritize target**: `%s` (%.0f%% success rate)\n"
                            (nth 0 best-target)
                            (* 100 (nth 3 best-target))))))
        ;; Find best category
        (when category-stats
          (let ((best-cat (car category-stats)))
            (insert (format "- **Prioritize change type**: %s (%.0f%% merge rate)\n"
                            (pcase (nth 0 best-cat)
                              ('bug-fix "bug fixes")
                              ('performance "performance improvements")
                              ('refactoring "refactoring")
                              ('safety "safety checks")
                              ('feature "new features")
                              (_ "other changes"))
                            (* 100 (nth 3 best-cat))))))
        (insert "\n"))

      (message "[auto-workflow] Synthesized knowledge to %s" knowledge-file)
      ;; Invalidate auto-workflow-evolution cache
      (when (fboundp 'gptel-auto-workflow--knowledge-cache-invalidate)
        (gptel-auto-workflow--knowledge-cache-invalidate 'auto-workflow-evolution)
        (message "[knowledge-cache] Invalidated auto-workflow-evolution")))))

;; ─── Prompt Integration ───

(defun gptel-auto-workflow--mementum-get-knowledge-for-prompt ()
  "Get synthesized knowledge text for prompt injection.
Returns a string or empty string if no knowledge available.
Uses cache to avoid repeated file reads."
  (let ((cached (when (fboundp 'gptel-auto-workflow--knowledge-cache-get)
                  (gptel-auto-workflow--knowledge-cache-get 'auto-workflow-evolution))))
    (if cached
        (progn
          (message "[knowledge-cache] Hit for auto-workflow-evolution (%d chars)" (length cached))
          cached)
      (let* ((knowledge-file (expand-file-name
                              "mementum/knowledge/auto-workflow-evolution.md"
                              (gptel-auto-workflow--worktree-base-root))))
        (if (file-exists-p knowledge-file)
            (let ((content
                   (with-temp-buffer
                     (insert-file-contents knowledge-file)
                     ;; Skip frontmatter
                     (goto-char (point-min))
                     (when (looking-at "---")
                       (forward-line 1)
                       (while (not (looking-at "---"))
                         (forward-line 1))
                       (forward-line 1))
                     (let ((content (buffer-string)))
                       (if (> (length content) 2000)
                           (concat (substring content 0 1500)
                                   "\n\n... [truncated for brevity] ...")
                         content)))))
              (when (fboundp 'gptel-auto-workflow--knowledge-cache-set)
                (gptel-auto-workflow--knowledge-cache-set 'auto-workflow-evolution content)
                (message "[knowledge-cache] Miss for auto-workflow-evolution, cached %d chars"
                         (length content)))
              content)
          "")))))

;; ─── Batch Job ───

(defun gptel-auto-workflow-mementum-weekly-job ()
  "Run weekly synthesis of experiment memories into knowledge.
Call this from a cron job or timer."
  (interactive)
  (message "[auto-workflow] Running weekly mementum synthesis...")
  (gptel-auto-workflow--mementum-synthesize-knowledge)
  (message "[auto-workflow] Mementum synthesis complete."))

(provide 'gptel-auto-workflow-mementum)
;;; gptel-auto-workflow-mementum.el ends here
