;;; gptel-auto-workflow-research-digest.el --- Synthesized Research Digest -*- lexical-binding:t -*-

;; Synthesized from all research findings across multiple researcher turns.
;; Sources: davidwuchn/* repos (zeroclaw, nullclaw, eca, context-mode, ai-code-interface),
;;          upstream gptel/karthink, gptel-agent, external arXiv papers,
;;          Azure AI Agent Design Patterns, MCP integration patterns.
;;
;; Hash: a92f6b43f26e39beda68c87725394cf10657da83
;; Generated: 2026-05-31
;; Research turns: 24 total, 11 non-empty, 17% kept (4/24)

;;; Commentary:
;; This module contains the synthesized knowledge digest from all research.
;; It is READ-ONLY — do not edit manually.  Auto-generated by researcher daemon.

;;; Code:

(defvar gptel-research-digest--version "2026-05-31"
  "Research digest version tag.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; SECTION 1: OWN REPOS — davidwuchn/* PATTERNS (53% of research budget)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1A. ZEROCLAW (Rust) — Agent Runtime Core
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/zeroclaw
;; Provider-agnostic AI runtime, multi-channel, SOP engine, security-first
(defvar gptel-research-zeroclaw-patterns
  '(;; PROVIDER-AGNOSTIC CORE
    ;; Architecture: pluggable LLM backends via vtable interfaces.
    ;; Zero-coupling to any specific provider's API quirks.
    ;; Add new provider by implementing interface, no core changes.
    (:provider-abstraction
     "Pluggable LLM backends via vtable interfaces. Zero coupling to provider API."
     :apply-to-us "Implement gptel-backend as cl-defgeneric with per-provider methods."
     :status "PARTIAL — gptel has this, ECA subagents need it.")

    ;; MULTI-CHANNEL ADAPTERS
    ;; 30+ channels: Discord, Telegram, Matrix, CLI, VSCode, Neovim, etc.
    ;; Channel is input/output modality, not just messaging.
    (:multi-channel
     "30+ adapters for input/output modalities (Discord, CLI, IDE, etc.)"
     :apply-to-us "Multi-channel not needed in Emacs, but adapter pattern for tools yes."
     :status "NOT_NEEDED — Emacs is single-channel by nature.")

    ;; SOP ENGINE
    ;; Standard Operating Procedures: event-triggered workflows.
    ;; Chain-of-thought with explicit step sequencing.
    (:sop-engine
     "Event-triggered SOP engine: chains formal reasoning steps as workflows."
     :apply-to-us "Implement SOP as structured workflow definitions in auto-workflow."
     :status "IMPLEMENTED — gptel-auto-workflow uses step sequences.")

    ;; SECURITY POLICY + WORKSPACE BOUNDARIES
    ;; OS-level sandboxing (Landlock/Bubblewrap/Seatbelt).
    ;; Command policy (allowed/forbidden patterns).
    ;; Tool receipts for audit trail.
    (:security-policy
     "Workspace boundaries, command policy, tool receipts, OS-level sandboxing."
     :apply-to-us "Implement gptel-tool-permits with pattern matching for shell commands."
     :status "IMPLEMENTED — gptel-ext-tool-permits.el exists.")

    ;; FALLBACK CHAINS
    ;; Provider A fails → Provider B → Provider C.
    ;; Explicit priority ordering with health tracking.
    (:fallback-chains
     "Priority-ordered provider fallback with health tracking."
     :apply-to-us "Implement multi-backend failover in provider-error-analyzer."
     :status "IMPLEMENTED — gptel-tools-agent-error.el has fallback logic.")

    ;; TOOL RECEIPTS
    ;; Every tool execution logged with cryptographic metadata.
    ;; Enables replay and compliance audit.
    (:tool-receipts
     "Structured metadata for every tool execution: input-hash, output-hash, timestamp."
     :apply-to_us "Implement gptel-tool-log using sqlite for audit trail."
     :status "PARTIAL — basic logging exists, receipts needed.")
    )
  "Zeroclaw agent runtime patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1B. NULLCLAW (Zig) — Minimal Infrastructure
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/nullclaw
;; 678 KB binary, ~1MB RAM, <2ms startup. No runtime, no GC.
(defvar gptel-research-nullclaw-patterns
  '(;; MINIMAL BINARY PRINCIPLE
    (:lean-binary
     "678KB static binary, ~1MB RAM, <2ms startup. No runtime, no GC."
     :apply-to_us "Target leaner elisp modules. Use byte-compile aggressively."
     :status "ASPIRATIONAL — Elisp is interpreted, but minimize dependencies.")

    ;; VTABLE INTERFACES
    ;; Providers, channels, tools, memory, peripherals all pluggable.
    (:vtable-interfaces
     "Pluggable providers, channels, tools, memory engines via vtable interfaces."
     :apply-to_us "Define cl-defgeneric for each abstraction point in ECA."
     :status "PARTIAL — backend abstraction exists in gptel.")

    ;; MULTI-LAYER SANDBOX
    ;; landlock → firejail → bubblewrap → docker escalation.
    ;; Each layer adds isolation at different cost points.
    (:multi-layer-sandbox
     "Landlock → firejail → bubblewrap → docker escalation chain."
     :apply-to_us "Implement graduated sandbox levels in gptel-sandbox.el."
     :status "IMPLEMENTED — gptel-sandbox.el exists.")

    ;; WORKSPACE SCOPING
    ;; Agents operate within bounded workspace, can't escape.
    (:workspace-scoping
     "Workspace boundary enforcement: agent cannot escape designated scope."
     :apply-to_us "Implement bounded workspace context in auto-workflow."
     :status "IMPLEMENTED — auto-workflow operates within project scope.")

    ;; ENCRYPTED SECRETS
    ;; API keys never in plain text, decrypted per-session.
    (:encrypted-secrets
     "Encrypted secrets, decrypted per-session, never plain text."
     :apply-to_us "Use auth-source or gpg-encrypted .env for API keys."
     :status "IMPLEMENTED — gptel uses auth-source.")
    )
  "Nullclaw minimal infrastructure patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1C. ECA (Clojure) — Editor Code Assistant
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/eca
;; Editor-agnostic protocol, multi-model, multi-agent, LSP-inspired
(defvar gptel-research-eca-patterns
  '(;; EDITOR-AGNOSTIC PROTOCOL
    ;; LSP-inspired protocol: language-agnostic, editor-agnostic.
    ;; stdin/stdout JSON-RPC communication.
    (:editor-agnostic-protocol
     "LSP-inspired stdin/stdout JSON-RPC protocol for editor-agnostic agents."
     :apply-to_us "ECA already IS the Emacs integration layer. Extend via MCP."
     :status "IMPLEMENTED — ECA IS this protocol.")

    ;; MULTI-MODEL SUPPORT
    ;; Claude, GPT, Gemini, local models with unified interface.
    (:multi-model
     "Unified interface across Claude, GPT, Gemini, local models."
     :apply-to_us "gptel already handles multi-model. ECA wraps gptel."
     :status "IMPLEMENTED — gptel has multiple backends.")

    ;; MULTI-AGENT / SUBAGENT
    ;; Supervisor agent delegates to specialized subagents.
    ;; Subagents have bounded context and return concise reports.
    (:multi-agent-delegation
     "Supervisor delegates to specialized subagents with bounded context."
     :apply-to_us "Extend ECA subagent system with explicit capability matching."
     :status "IMPLEMENTED — ECA has code/plan/executor subagents.")

    ;; MCP RESOURCES
    ;; MCP servers provide tools and resources to agents.
    (:mcp-resources
     "Model Context Protocol for external tool/resource discovery."
     :apply-to_us "Integrate mcp.el for external tool server discovery."
     :status "PARTIAL — gptel has MCP support, ECA needs it.")

    ;; CONTEXT SUPPORT
    ;; Structured context passing between supervisor and subagents.
    (:structured-context
     "Structured context passing with capability requirements."
     :apply-to_us "Add capability tags to subagent requests in ECA."
     :status "PARTIAL — context passed but not capability-tagged.")
    )
  "ECA editor code assistant patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1D. CONTEXT-MODE (TypeScript) — Context Window Optimization
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/context-mode
;; 98% context reduction, sandbox tools, session continuity
(defvar gptel-research-context-mode-patterns
  '(;; THINK-IN-CODE (98% REDUCTION)
    ;; Instead of dumping 700KB via 47× Read() calls,
    ;; agent writes script that computes and returns only the answer.
    ;; 315KB → 5.4KB via sandbox tool execution.
    (:think-in-code
     "Execute analysis script, return only answer. 98%% context reduction."
     :apply-to_us "Implement gptel-sandbox-execute for analysis scripts."
     :status "HIGH_PRIORITY — implement in gptel-sandbox.el")

    ;; SESSION CONTINUITY
    ;; Every edit, git op, task, error tracked in SQLite with FTS5.
    ;; On context compaction, retrieves only relevant events.
    (:session-continuity
     "SQLite/FTS5 event indexing. Only relevant events retrieved on compaction."
     :apply-to_us "Implement gptel-session-db using sqlite.el."
     :status "HIGH_PRIORITY — session continuity critical for long runs.")

    ;; OUTPUT COMPRESSION
    ;; Verbose tool outputs compressed before LLM consumption.
    ;; Structured summaries instead of raw data.
    (:output-compression
     "Tool outputs compressed to structured summaries before LLM context."
     :apply-to_us "Implement compression in gptel-tools before appending to context."
     :status "IMPLEMENTED — context-mode already does this.")

    ;; SESSION INDEXING
    ;; BM25 + embedding hybrid search over session events.
    ;; Not raw dumps — curated retrieval.
    (:hybrid-retrieval
     "BM25 + embedding hybrid search over session events."
     :apply-to_us "Add hybrid retrieval to gptel-session-db."
     :status "FUTURE — FTS5 exists, embedding search not yet.")
    )
  "Context-mode patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1E. AI-CODE-INTERFACE.EL — Unified Emacs Interface
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/ai-code-interface.el
;; Unified interface for Codex, Copilot CLI, Claude Code, Gemini, Opencode
(defvar gptel-research-ai-code-interface-patterns
  '(;; UNIFIED PROVIDER INTERFACE
    ;; Single interface across OpenAI Codex, Copilot CLI, Claude Code, Gemini CLI.
    (:unified-interface
     "Single interface pattern across multiple AI providers."
     :apply-to_us "gptel IS this. Extend with additional backends."
     :status "IMPLEMENTED — gptel has multiple backends.")

    ;; PROVIDER CAPABILITY TAGS
    ;; Each provider tagged with capabilities (vision, function-calling, etc.)
    (:capability-tags
     "Provider capability tags for intelligent routing."
     :apply-to_us "Add capability tags to gptel-backend definitions."
     :status "PARTIAL — some tags exist, not comprehensive.")
    )
  "AI-code-interface patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 1F. ORI-MNEMOS (TypeScript) — Persistent Agentic Memory
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/davidwuchn/ori-mnemos
;; Local-first persistent memory, Recursive Memory Harness (RMH)
(defvar gptel-research-ori-mnemos-patterns
  '(;; LOCAL-FIRST MEMORY
    ;; Markdown files + wiki-links as graph structure.
    ;; SQLite for indexing. No cloud dependency.
    (:local-first-memory
     "Markdown + wiki-links graph, SQLite indexing, no cloud."
     :apply-to_us "Use mementum/local notes for memory, sqlite.el for indexing."
     :status "IMPLEMENTED — mementum state.md exists.")

    ;; RECURSIVE MEMORY HARNESS
    ;; Memory references other memories, creating recursive chains.
    ;; Retrieval traverses chains rather than flat search.
    (:recursive-memory
     "Memory chains: each memory can reference other memories recursively."
     :apply-to_us "Implement recursive memory traversal in mementum.el."
     :status "FUTURE — flat memories exist, recursive needed.")

    ;; HYBRID RETRIEVAL
    ;; BM25 + embedding + PageRank for retrieval.
    ;; Competitive with Mem0 on MMLU-Pro, 30% lower cost.
    (:hybrid-retrieval-mem
     "BM25 + embedding + PageRank hybrid retrieval. Competitive with Mem0."
     :apply-to_us "Add PageRank-based importance scoring to memory retrieval."
     :status "FUTURE — BM25 exists, PageRank not yet.")
    )
  "Ori-Mnemos memory patterns for Emacs adaptation.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; SECTION 2: UPSTREAM GPTEL — Karthink Patterns (15% of research budget)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 2A. GPTEL — LLM Client for Emacs
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/karthink/gptel
(defvar gptel-research-gptel-patterns
  '(;; FSM REQUEST LIFECYCLE
    ;; INIT → WAIT → TYPE → TOOL → DONE
    ;; Each state has entry/exit actions.
    (:fsm-lifecycle
     "FSM request lifecycle: INIT→WAIT→TYPE→TOOL→DONE with state actions."
     :apply-to_us "Use FSM for auto-workflow request lifecycle."
     :status "IMPLEMENTED — gptel-ext-fsm.el exists")

    ;; TOOL USE
    ;; gptel-make-tool defines structured tools with name/description/parameters.
    ;; Confirmation before execution. Curl/url-retrieve dual backend.
    (:tool-use-architecture
     "Structured tool specs with confirmation, dual curl/url-retrieve backend."
     :apply-to_us "Use gptel-make-tool for all agent tools. Don't invent new format."
     :status "IMPLEMENTED — gptel has tool infrastructure.")

    ;; MCP INTEGRATION
    ;; mcp.el for Model Context Protocol. External tool servers.
    (:mcp-integration
     "MCP via mcp.el for external tool server discovery."
     :apply-to_us "Integrate mcp.el in ECA. mcp-hub for multi-server management."
     :status "PARTIAL — gptel supports MCP, ECA needs integration.")

    ;; PRESET SYSTEM
    ;; Bundled configuration for model/provider combinations.
    ;; gptel-org-branching-context for independent questions.
    (:preset-system
     "Preset system for bundled configuration. Branching context for parallel questions."
     :apply-to_us "Use presets for auto-workflow experiment configurations."
     :status "PARTIAL — presets exist, branching not in auto-workflow.")

    ;; MULTI-MODAL
    ;; Images and documents supported via base64.
    (:multimodal
     "Images/documents via base64 encoding."
     :apply-to_us "Support screenshots in bug reports and error analysis."
     :status "IMPLEMENTED — gptel handles this.")

    ;; TEMPERATURE NIL DEFAULT
    ;; Backend-specific temperature defaults. Nil means API default.
    (:temperature-default
     "Temperature nil delegates to backend default. Backends disagree on scale."
     :apply-to_us "Set temperature nil in auto-workflow unless specific behavior needed."
     :status "IMPLEMENTED.")
    )
  "gptel upstream patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 2B. GPTEL-AGENT — Sub-Agent Delegation Package
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://github.com/karthink/gptel-agent
;; Sub-agent delegation via Markdown/YAML frontmatter
(defvar gptel-research-gptel-agent-patterns
  '(;; DECLARATIVE AGENT SPECS
    ;; Agent definitions as Markdown files with YAML frontmatter.
    ;; name, description, tools, pre-hook in frontmatter.
    ;; NOT in code — declarative, version-controllable.
    (:declarative-agent-specs
     "Markdown/YAML frontmatter agent specs: name, description, tools, pre-hook."
     :apply-to_us "Convert ECA subagents from code to declarative YAML files."
     :status "HIGH_PRIORITY — declarative specs more maintainable")

    ;; CONTEXT ISOLATION
    ;; Sub-agents don't share context with main session.
    ;; Returns concise reports, not full conversation.
    (:context-isolation
     "Sub-agents with isolated context, return concise reports."
     :apply-to_us "ECA subagents should return structured reports, not full context."
     :status "IMPLEMENTED — ECA does this")

    ;; SKILL DIRECTORY SCANNING
    ;; gptel-agent-skill-dirs scans ~/.claude/skills/, .agents/skills/
    ;; Auto-discovers skills from filesystem.
    (:skill-directory-scanning
     "Skill directory auto-scanning: ~/.claude/skills/, .agents/skills/"
     :apply-to_us "Implement skill auto-discovery in ECA."
     :status "FUTURE — manual skill loading exists.")

    ;; SUB-AGENT TYPES
    ;; executor (autonomous, full tools), researcher (read-only),
    ;; introspector (Emacs introspection), reviewer.
    (:subagent-types
     "Sub-agent types: executor, researcher, introspector, reviewer."
     :apply-to_us "ECA already has code/plan/executor/reviewer types."
     :status "IMPLEMENTED")

    ;; @MENTION DELEGATION
    ;; Include @agent-name in prompt to delegate.
    ;; Natural language delegation syntax.
    (:mention-delegation
     "Natural language @agent-name delegation syntax."
     :apply-to_us "Implement @mention delegation in ECA prompt parser."
     :status "PARTIAL — exists but not fully natural.")

    ;; PLANNING VS EXECUTION PRESETS
    ;; gptel-plan (read-only) vs gptel-agent (full tools).
    (:plan-vs-execute
     "Planning (read-only) vs execution (full tools) presets."
     :apply-to_us "Auto-workflow should have distinct plan vs execute modes."
     :status "IMPLEMENTED — research vs apply phases exist.")
    )
  "gptel-agent patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; SECTION 3: EXTERNAL PATTERNS (32% of research budget)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 3A. ARXIV — Multi-Agent Orchestration (2601.13671v1)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; arXiv:2409.17487 — Comprehensive multi-agent design patterns
(defvar gptel-research-arxiv-orchestration-patterns
  '(;; ORCHESTRATION LAYER ARCHITECTURE
    ;; Planning → Policy → Execution → State → Quality Ops
    ;; Clean separation of concerns.
    (:orchestration-layer
     "Orchestration layer: Planning→Policy→Execution→State→Quality Ops"
     :apply-to_us "Map auto-workflow phases to these 5 layers explicitly."
     :status "PARTIAL — phases exist but not mapped to architecture.")

    ;; STATE/KNOWLEDGE SEPARATION
    ;; Operational state ≠ knowledge state. Preserves modularity.
    (:state-knowledge-separation
     "Separate operational state from knowledge state for modularity."
     :apply-to_us "Experiment state (operational) vs learned patterns (knowledge)."
     :status "IMPLEMENTED — state.md vs memories/knowledge/")

    ;; MCP PROTOCOL
    ;; Agent → Tool server communication standard.
    (:mcp-protocol
     "MCP: Model Context Protocol for agent-tool communication."
     :apply-to_us "Use MCP for all external tool discovery in ECA."
     :status "PARTIAL — gptel supports, ECA needs integration.")

    ;; A2A PROTOCOL
    ;; Agent-to-agent communication standard.
    (:a2a-protocol
     "A2A: Agent-to-Agent communication protocol."
     :apply-to_us "ECA subagents communicate via structured messages, not shared context."
     :status "IMPLEMENTED — ECA uses report-based communication.")
    )
  "arXiv multi-agent orchestration patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 3B. AZURE AI AGENT DESIGN PATTERNS
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://learn.microsoft.com/azure/architecture/ai-ml/guide/ai-agent-design-patterns
(defvar gptel-research-azure-patterns
  '(;; COMPLEXITY SPECTRUM
    ;; Direct call → Single agent+Tools → Sequential → Concurrent → Hierarchical
    ;; Use lowest complexity that reliably meets requirements.
    (:complexity-spectrum
     "5-level complexity: Direct→Agent+Tools→Sequential→Concurrent→Hierarchical"
     :apply-to_us "Auto-workflow sits at Level 2-3. Don't escalate without need."
     :status "IMPLEMENTED")

    ;; CONCURRENT ORCHESTRATION
    ;; Fan-out/fan-in: multiple agents process in parallel, results aggregated.
    ;; For independent parallel tasks.
    (:concurrent-orchestration
     "Fan-out/fan-in: parallel agents, aggregated results."
     :apply-to_us "Run multiple experiment variants concurrently."
     :status "HIGH_PRIORITY — implement parallel experiment runner.")

    ;; GROUP CHAT / MAKER-CHECKER
    ;; Turn-based: maker creates, checker validates, iterate until acceptance.
    ;; Explicit acceptance criteria, iteration caps.
    (:maker-checker-loop
     "Maker-checker: create→validate→iterate, with acceptance criteria."
     :apply-to_us "Implement code-review loop: writer agent + reviewer agent."
     :status "HIGH_PRIORITY — critical for quality.")

    ;; TASK LEDGER (MAGENTIC)
    ;; Manager builds task ledger (plan with goals/subgoals) dynamically.
    ;; Delegates to specialized agents with explicit tracking.
    (:task-ledger
     "Dynamic task ledger: plan with goals/subgoals, explicit delegation tracking."
     :apply-to_us "Add structured task ledger to auto-workflow projects."
     :status "MEDIUM_PRIORITY")

    ;; FALLBACK CHAINS
    ;; Priority-ordered provider list with automatic failover.
    (:fallback-chains-azure
     "Priority-ordered provider fallback with automatic failover."
     :apply-to_us "Implement in provider-error-analyzer."
     :status "IMPLEMENTED")
    )
  "Azure AI agent design patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 3C. ARXIV — ACON: Context Compression (2510.00615)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; ACON: Iterative Compression Guideline Optimization
(defvar gptel-research-acon-patterns
  '(;; ITERATIVE COMPRESSION GUIDELINE OPTIMIZATION
    ;; LLM analyzes WHY compressed context failed, updates guidelines.
    ;; Iterative refinement cycle: compress → test → analyze → update.
    ;; 26-54% memory reduction, >95% accuracy preserved.
    (:acon-compression
     "Iterative compression: LLM analyzes failures, updates guidelines. 26-54%% reduction."
     :apply-to_us "Implement gptel-tools-compress with iterative refinement."
     :status "HIGH_PRIORITY — 98%% reduction available")

    ;; NOVELTY: FAILURE-DRIVEN LEARNING
    ;; Compression improves by learning from mistakes, not static rules.
    (:failure-driven-compression
     "Compression improves by learning from context failures."
     :apply-to_us "Track which compressions caused accuracy loss, adapt."
     :status "FUTURE")
    )
  "ACON context compression patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 3D. ARXIV — Agent Memory Survey (2603.07670v1)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; Comprehensive memory mechanism taxonomy for autonomous LLM agents
(defvar gptel-research-memory-survey-patterns
  '(;; WRITE-MANAGE-READ LOOP
    ;; Five mechanism families:
    ;; 1. Context-resident compression
    ;; 2. Retrieval-augmented stores
    ;; 3. Reflective self-improvement
    ;; 4. Hierarchical virtual context
    ;; 5. Policy-learned management
    (:memory-taxonomy
     "5 memory families: context-compress, RAG, reflective, hierarchical, policy-learned"
     :apply-to_us "Our mementum covers #1, #2, #3. Need #4 hierarchical + #5 policy."
     :status "PARTIAL")

    ;; REFLECTIVE SELF-IMPROVEMENT
    ;; Agent reflects on past actions, extracts patterns, modifies behavior.
    (:reflective-improvement
     "Reflective self-improvement: extract patterns from past actions."
     :apply-to_us "Implement in auto-workflow evolution module."
     :status "IMPLEMENTED — auto-workflow-evolution does this")

    ;; HIERARCHICAL VIRTUAL CONTEXT
    ;; Multiple context layers: working → recent → historical → long-term.
    (:hierarchical-context
     "Hierarchical context: working→recent→historical→long-term layers."
     :apply-to_us "Implement context layer hierarchy in auto-workflow."
     :status "FUTURE")
    )
  "Agent memory survey patterns.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; 3E. CALLSPHERE — Error Recovery Patterns
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; https://callsphere.ai/blog/agent-error-recovery-patterns/
(defvar gptel-research-error-recovery-patterns
  '(;; CIRCUIT BREAKER WITH STATES
    ;; CLOSED (normal) → OPEN (blocked) → HALF_OPEN (testing recovery)
    ;; Per-model circuit breakers for isolation.
    (:circuit-breaker
     "Circuit breaker: CLOSED→OPEN→HALF_OPEN states. Per-model isolation."
     :apply-to_us "Implement in provider-error-analyzer with state tracking."
     :status "PARTIAL — basic circuit breaker exists")

    ;; ERROR CLASSIFICATION
    ;; Retryable (transient) vs fatal (permanent) errors.
    ;; Different handling for each category.
    (:error-classification
     "Error classification: retryable (transient) vs fatal (permanent)."
     :apply-to_us "Sharpening retryable/fatal distinction in provider-error-analyzer."
     :status "IMPLEMENTED")

    ;; SELF-CORRECTION LOOPS
    ;; Output validators check results before returning to context.
    (:self-correction
     "Self-correction: output validators check results before context return."
     :apply-to_us "Add structured validators to auto-workflow verification."
     :status "PARTIAL — grader agent does this")

    ;; GRACEFUL DEGRADATION
    ;; Capability flags: disable risky tools after failures.
    (:graceful-degradation
     "Graceful degradation: capability flags disable risky features after failures."
     :apply-to_us "After 3 failures → disable risky tools, add human review."
     :status "FUTURE")
    )
  "Error recovery patterns from callsphere.ai.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; SECTION 4: SYNTHESIS — HIGHEST PRIORITY ACTIONS
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

(defvar gptel-research-highest-priority
  '(;; CRITICAL GAPS — Do first
    (:critical-1
     "Think-in-Code Context Reduction"
     "Implement gptel-sandbox-execute for analysis scripts. 98%% reduction available."
     "gptel-sandbox.el"
     3)

    (:critical-2
     "Session Continuity DB"
     "Implement gptel-session-db using sqlite.el. Session continuity critical."
     "gptel-session-db.el (new)"
     3)

    (:critical-3
     "Concurrent Experiment Runner"
     "Implement fan-out/fan-in parallel experiment execution."
     "gptel-auto-workflow-projects.el"
     2)

    (:critical-4
     "Maker-Checker Code Loop"
     "Implement reviewer agent with acceptance criteria and iteration caps."
     "gptel-tools-agent-review.el (new)"
     2)

    ;; HIGH PRIORITY
    (:high-1
     "Declarative Agent Specs"
     "Convert ECA subagents from code to YAML frontmatter files."
     "eca-subagents/ (new dir)"
     2)

    (:high-2
     "ACON-Style Compression"
     "Implement iterative compression guideline optimization."
     "gptel-tools-compress.el (new)"
     2)

    (:high-3
     "Task Ledger"
     "Add structured task ledger to auto-workflow projects."
     "gptel-auto-workflow-projects.el"
     1)

    (:high-4
     "Skill Auto-Discovery"
     "Implement skill directory scanning for ECA."
     "eca-skills/ (new dir)"
     1)
    )
  "Highest priority research-backed actions, sorted by impact and difficulty.")

;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
;; SECTION 5: WHAT WE ALREADY HAVE (AVOID DUPLICATION)
;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

(defvar gptel-research-already-implemented
  '(;; FROM OWN REPOS
    "Provider abstraction — gptel has multi-backend support"
    "Fallback chains — gptel-tools-agent-error.el has fallback logic"
    "Security policy — gptel-ext-tool-permits.el exists"
    "Workspace scoping — auto-workflow operates within project scope"
    "SOP engine — step sequences in auto-workflow"
    "Multi-model — gptel has multiple backends"
    "Multi-agent — ECA has code/plan/executor/reviewer subagents"
    "Context isolation — ECA subagents return concise reports"
    "Output compression — context-mode already does this"
    "Local-first memory — mementum state.md exists"
    "FSM lifecycle — gptel-ext-fsm.el exists"
    "Tool infrastructure — gptel-make-tool available"
    "MCP support — gptel has MCP integration"
    "Temperature nil — default in gptel"
    "Error classification — provider-error-analyzer has retryable/fatal"
    "Self-correction — grader agent in auto-workflow"
    "Reflective improvement — auto-workflow-evolution.el"
    ;; FROM EXTERNAL PATTERNS
    "VSM architecture — mapped to S1-S5 in auto-workflow"
    "OODA control loops — error-driven learning loop in auto-workflow"
    "Fibonacci recall — not explicitly, but depth tracking exists"
    "Meta-learning λ(λ) — basic learning exists, not formal λ(λ)"
    "Mode/boundary system — partial, modes exist without explicit will_not_do"
    "Symbolic attention magnets — nucleus preamble in system prompt"
    )
  "Patterns already implemented — do NOT duplicate.")

(provide 'gptel-auto-workflow-research-digest)
;;; gptel-auto-workflow-research-digest.el ends here
